<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?scdStore version="2"?>

<scannerInfo id="org.eclipse.cdt.make.core.discoveredScannerInfo">
<instance id="com.arc.cdt.toolchain.arc.exeDebugConfig.692587;com.arc.cdt.toolchain.arc.exeDebugConfig.692587.1723546996;arc.exe.debug.exeCompilerDebug.1651698080;com.arc.cdt.toolchain.arc.inputTypeC.136622268">
<collector id="org.eclipse.cdt.make.core.PerProjectSICollector">
<includePath path="C:\ARC\MetaWare\arc/inc"/>
<includePath path="C:\ARC\MetaWare\arc/incc"/>
<definedSymbol symbol="__HIGHC__"/>
<definedSymbol symbol="_GOC=1"/>
<definedSymbol symbol="_ARC=1"/>
<definedSymbol symbol="_ATT4=1"/>
<definedSymbol symbol="__HAS_LONGLONG=1"/>
<definedSymbol symbol="_ARCOMPACT=1"/>
<definedSymbol symbol="_ARCVER=0x21"/>
<definedSymbol symbol="__Xbarrel_shifter=1"/>
<definedSymbol symbol="_Interrupt1=_CC(_INTERRUPT1|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Interrupt2=_CC(_INTERRUPT2|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Exception=_CC(_EXCEPTION|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Preserve_flags=_CC(_PRESERVE_FLAGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Save_all_regs=_CC(_SAVE_ALL_REGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Never_returns=_CC(_NEVER_RETURNS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="__arc__=1"/>
<definedSymbol symbol="_ARC_LE=1"/>
<definedSymbol symbol="_LE=1"/>
<definedSymbol symbol="_REENTRANT=1"/>
<definedSymbol symbol="_MT=1"/>
</collector>
</instance>
<instance id="com.arc.cdt.toolchain.arc.exeDebugConfig.692587;com.arc.cdt.toolchain.arc.exeDebugConfig.692587.1723546996;arc.exe.debug.exeCompilerDebug.1651698080;com.arc.cdt.toolchain.arc.inputTypeCPP.656182325">
<collector id="org.eclipse.cdt.make.core.PerProjectSICollector">
<includePath path="C:\ARC\MetaWare\arc/inc"/>
<includePath path="C:\ARC\MetaWare\arc/incc"/>
<definedSymbol symbol="__HIGHC__"/>
<definedSymbol symbol="_GOC=1"/>
<definedSymbol symbol="_ARC=1"/>
<definedSymbol symbol="_ATT4=1"/>
<definedSymbol symbol="__HAS_LONGLONG=1"/>
<definedSymbol symbol="_ARCOMPACT=1"/>
<definedSymbol symbol="_ARCVER=0x21"/>
<definedSymbol symbol="__Xbarrel_shifter=1"/>
<definedSymbol symbol="_Interrupt1=_CC(_INTERRUPT1|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Interrupt2=_CC(_INTERRUPT2|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Exception=_CC(_EXCEPTION|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Preserve_flags=_CC(_PRESERVE_FLAGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Save_all_regs=_CC(_SAVE_ALL_REGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Never_returns=_CC(_NEVER_RETURNS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="__arc__=1"/>
<definedSymbol symbol="_ARC_LE=1"/>
<definedSymbol symbol="_LE=1"/>
<definedSymbol symbol="_REENTRANT=1"/>
<definedSymbol symbol="_MT=1"/>
</collector>
</instance>
<instance id="com.arc.cdt.toolchain.arc.exeReleaseConfig.531153;com.arc.cdt.toolchain.arc.exeReleaseConfig.531153.1876446735;arc.cdt.toolchain.arc.exeCompilerRelease.270300290;com.arc.cdt.toolchain.arc.inputTypeC.333234245">
<collector id="org.eclipse.cdt.make.core.PerProjectSICollector">
<includePath path="C:\ARC\MetaWare\arc/inc"/>
<includePath path="C:\ARC\MetaWare\arc/incc"/>
<definedSymbol symbol="__HIGHC__"/>
<definedSymbol symbol="_GOC=1"/>
<definedSymbol symbol="_ARC=1"/>
<definedSymbol symbol="_ATT4=1"/>
<definedSymbol symbol="__HAS_LONGLONG=1"/>
<definedSymbol symbol="_ARCOMPACT=1"/>
<definedSymbol symbol="_ARCVER=0x21"/>
<definedSymbol symbol="__Xbarrel_shifter=1"/>
<definedSymbol symbol="_Interrupt1=_CC(_INTERRUPT1|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Interrupt2=_CC(_INTERRUPT2|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Exception=_CC(_EXCEPTION|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Preserve_flags=_CC(_PRESERVE_FLAGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Save_all_regs=_CC(_SAVE_ALL_REGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Never_returns=_CC(_NEVER_RETURNS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="__arc__=1"/>
<definedSymbol symbol="_ARC_LE=1"/>
<definedSymbol symbol="_LE=1"/>
<definedSymbol symbol="_REENTRANT=1"/>
<definedSymbol symbol="_MT=1"/>
</collector>
</instance>
<instance id="com.arc.cdt.toolchain.arc.exeReleaseConfig.531153;com.arc.cdt.toolchain.arc.exeReleaseConfig.531153.1876446735;arc.cdt.toolchain.arc.exeCompilerRelease.270300290;com.arc.cdt.toolchain.arc.inputTypeCPP.1412808225">
<collector id="org.eclipse.cdt.make.core.PerProjectSICollector">
<includePath path="C:\ARC\MetaWare\arc/inc"/>
<includePath path="C:\ARC\MetaWare\arc/incc"/>
<definedSymbol symbol="__HIGHC__"/>
<definedSymbol symbol="_GOC=1"/>
<definedSymbol symbol="_ARC=1"/>
<definedSymbol symbol="_ATT4=1"/>
<definedSymbol symbol="__HAS_LONGLONG=1"/>
<definedSymbol symbol="_ARCOMPACT=1"/>
<definedSymbol symbol="_ARCVER=0x21"/>
<definedSymbol symbol="__Xbarrel_shifter=1"/>
<definedSymbol symbol="_Interrupt1=_CC(_INTERRUPT1|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Interrupt2=_CC(_INTERRUPT2|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Exception=_CC(_EXCEPTION|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Preserve_flags=_CC(_PRESERVE_FLAGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Save_all_regs=_CC(_SAVE_ALL_REGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Never_returns=_CC(_NEVER_RETURNS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="__arc__=1"/>
<definedSymbol symbol="_ARC_LE=1"/>
<definedSymbol symbol="_LE=1"/>
<definedSymbol symbol="_REENTRANT=1"/>
<definedSymbol symbol="_MT=1"/>
</collector>
</instance>
<instance id="com.arc.cdt.toolchain.arc.exeDebugConfig.692587;com.arc.cdt.toolchain.arc.exeDebugConfig.692587.1723546996;arc.exe.debug.exeCompilerDebug.1651698080;com.arc.cdt.toolchain.arc.inputTypeC.1605507165">
<collector id="org.eclipse.cdt.make.core.PerProjectSICollector">
<includePath path="C:\ARC\MetaWare\arc/inc"/>
<includePath path="C:\ARC\MetaWare\arc/incc"/>
<definedSymbol symbol="__HIGHC__"/>
<definedSymbol symbol="_GOC=1"/>
<definedSymbol symbol="_ARC=1"/>
<definedSymbol symbol="_ATT4=1"/>
<definedSymbol symbol="__HAS_LONGLONG=1"/>
<definedSymbol symbol="_ARCOMPACT=1"/>
<definedSymbol symbol="_ARCVER=0x21"/>
<definedSymbol symbol="__Xbarrel_shifter=1"/>
<definedSymbol symbol="_Interrupt1=_CC(_INTERRUPT1|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Interrupt2=_CC(_INTERRUPT2|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Exception=_CC(_EXCEPTION|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Preserve_flags=_CC(_PRESERVE_FLAGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Save_all_regs=_CC(_SAVE_ALL_REGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Never_returns=_CC(_NEVER_RETURNS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="__arc__=1"/>
<definedSymbol symbol="_ARC_LE=1"/>
<definedSymbol symbol="_LE=1"/>
<definedSymbol symbol="_REENTRANT=1"/>
<definedSymbol symbol="_MT=1"/>
</collector>
</instance>
<instance id="com.arc.cdt.toolchain.arc.exeDebugConfig.692587;com.arc.cdt.toolchain.arc.exeDebugConfig.692587.1723546996;arc.exe.debug.exeCompilerDebug.1651698080;com.arc.cdt.toolchain.arc.inputTypeCPP.1297551768">
<collector id="org.eclipse.cdt.make.core.PerProjectSICollector">
<includePath path="C:\ARC\MetaWare\arc/inc"/>
<includePath path="C:\ARC\MetaWare\arc/incc"/>
<definedSymbol symbol="__HIGHC__"/>
<definedSymbol symbol="_GOC=1"/>
<definedSymbol symbol="_ARC=1"/>
<definedSymbol symbol="_ATT4=1"/>
<definedSymbol symbol="__HAS_LONGLONG=1"/>
<definedSymbol symbol="_ARCOMPACT=1"/>
<definedSymbol symbol="_ARCVER=0x21"/>
<definedSymbol symbol="__Xbarrel_shifter=1"/>
<definedSymbol symbol="_Interrupt1=_CC(_INTERRUPT1|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Interrupt2=_CC(_INTERRUPT2|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Exception=_CC(_EXCEPTION|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Preserve_flags=_CC(_PRESERVE_FLAGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Save_all_regs=_CC(_SAVE_ALL_REGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Never_returns=_CC(_NEVER_RETURNS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="__arc__=1"/>
<definedSymbol symbol="_ARC_LE=1"/>
<definedSymbol symbol="_LE=1"/>
<definedSymbol symbol="_REENTRANT=1"/>
<definedSymbol symbol="_MT=1"/>
</collector>
</instance>
<instance id="com.arc.cdt.toolchain.arc.exeReleaseConfig.531153;com.arc.cdt.toolchain.arc.exeReleaseConfig.531153.1876446735;arc.cdt.toolchain.arc.exeCompilerRelease.270300290;com.arc.cdt.toolchain.arc.inputTypeCPP.925968158">
<collector id="org.eclipse.cdt.make.core.PerProjectSICollector">
<includePath path="C:\ARC\MetaWare\arc/inc"/>
<includePath path="C:\ARC\MetaWare\arc/incc"/>
<definedSymbol symbol="__HIGHC__"/>
<definedSymbol symbol="_GOC=1"/>
<definedSymbol symbol="_ARC=1"/>
<definedSymbol symbol="_ATT4=1"/>
<definedSymbol symbol="__HAS_LONGLONG=1"/>
<definedSymbol symbol="_ARCOMPACT=1"/>
<definedSymbol symbol="_ARCVER=0x21"/>
<definedSymbol symbol="__Xbarrel_shifter=1"/>
<definedSymbol symbol="_Interrupt1=_CC(_INTERRUPT1|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Interrupt2=_CC(_INTERRUPT2|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Exception=_CC(_EXCEPTION|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Preserve_flags=_CC(_PRESERVE_FLAGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Save_all_regs=_CC(_SAVE_ALL_REGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Never_returns=_CC(_NEVER_RETURNS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="__arc__=1"/>
<definedSymbol symbol="_ARC_LE=1"/>
<definedSymbol symbol="_LE=1"/>
<definedSymbol symbol="_REENTRANT=1"/>
<definedSymbol symbol="_MT=1"/>
</collector>
</instance>
<instance id="com.arc.cdt.toolchain.arc.exeReleaseConfig.531153;com.arc.cdt.toolchain.arc.exeReleaseConfig.531153.1876446735;arc.cdt.toolchain.arc.exeCompilerRelease.270300290;com.arc.cdt.toolchain.arc.inputTypeC.453371470">
<collector id="org.eclipse.cdt.make.core.PerProjectSICollector">
<includePath path="C:\ARC\MetaWare\arc/inc"/>
<includePath path="C:\ARC\MetaWare\arc/incc"/>
<definedSymbol symbol="__HIGHC__"/>
<definedSymbol symbol="_GOC=1"/>
<definedSymbol symbol="_ARC=1"/>
<definedSymbol symbol="_ATT4=1"/>
<definedSymbol symbol="__HAS_LONGLONG=1"/>
<definedSymbol symbol="_ARCOMPACT=1"/>
<definedSymbol symbol="_ARCVER=0x21"/>
<definedSymbol symbol="__Xbarrel_shifter=1"/>
<definedSymbol symbol="_Interrupt1=_CC(_INTERRUPT1|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Interrupt2=_CC(_INTERRUPT2|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Exception=_CC(_EXCEPTION|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Preserve_flags=_CC(_PRESERVE_FLAGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Save_all_regs=_CC(_SAVE_ALL_REGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Never_returns=_CC(_NEVER_RETURNS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="__arc__=1"/>
<definedSymbol symbol="_ARC_LE=1"/>
<definedSymbol symbol="_LE=1"/>
<definedSymbol symbol="_REENTRANT=1"/>
<definedSymbol symbol="_MT=1"/>
</collector>
</instance>
<instance id="com.arc.cdt.toolchain.arc.exeDebugConfig.692587;com.arc.cdt.toolchain.arc.exeDebugConfig.692587.1723546996;arc.exe.debug.exeCompilerDebug.1651698080;com.arc.cdt.toolchain.arc.inputTypeCPP.905393418">
<collector id="org.eclipse.cdt.make.core.PerProjectSICollector">
<includePath path="C:\ARC\MetaWare\arc/inc"/>
<includePath path="C:\ARC\MetaWare\arc/incc"/>
<definedSymbol symbol="__HIGHC__"/>
<definedSymbol symbol="_GOC=1"/>
<definedSymbol symbol="_ARC=1"/>
<definedSymbol symbol="_ATT4=1"/>
<definedSymbol symbol="__HAS_LONGLONG=1"/>
<definedSymbol symbol="_ARCOMPACT=1"/>
<definedSymbol symbol="_ARCVER=0x21"/>
<definedSymbol symbol="__Xbarrel_shifter=1"/>
<definedSymbol symbol="_Interrupt1=_CC(_INTERRUPT1|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Interrupt2=_CC(_INTERRUPT2|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Exception=_CC(_EXCEPTION|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Preserve_flags=_CC(_PRESERVE_FLAGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Save_all_regs=_CC(_SAVE_ALL_REGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Never_returns=_CC(_NEVER_RETURNS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="__arc__=1"/>
<definedSymbol symbol="_ARC_LE=1"/>
<definedSymbol symbol="_LE=1"/>
<definedSymbol symbol="_REENTRANT=1"/>
<definedSymbol symbol="_MT=1"/>
</collector>
</instance>
<instance id="com.arc.cdt.toolchain.arc.exeDebugConfig.692587;com.arc.cdt.toolchain.arc.exeDebugConfig.692587.1723546996;arc.exe.debug.exeCompilerDebug.1651698080;com.arc.cdt.toolchain.arc.inputTypeC.436553077">
<collector id="org.eclipse.cdt.make.core.PerProjectSICollector">
<includePath path="C:\ARC\MetaWare\arc/inc"/>
<includePath path="C:\ARC\MetaWare\arc/incc"/>
<definedSymbol symbol="__HIGHC__"/>
<definedSymbol symbol="_GOC=1"/>
<definedSymbol symbol="_ARC=1"/>
<definedSymbol symbol="_ATT4=1"/>
<definedSymbol symbol="__HAS_LONGLONG=1"/>
<definedSymbol symbol="_ARCOMPACT=1"/>
<definedSymbol symbol="_ARCVER=0x21"/>
<definedSymbol symbol="__Xbarrel_shifter=1"/>
<definedSymbol symbol="_Interrupt1=_CC(_INTERRUPT1|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Interrupt2=_CC(_INTERRUPT2|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Exception=_CC(_EXCEPTION|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Preserve_flags=_CC(_PRESERVE_FLAGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Save_all_regs=_CC(_SAVE_ALL_REGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Never_returns=_CC(_NEVER_RETURNS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="__arc__=1"/>
<definedSymbol symbol="_ARC_LE=1"/>
<definedSymbol symbol="_LE=1"/>
<definedSymbol symbol="_REENTRANT=1"/>
<definedSymbol symbol="_MT=1"/>
</collector>
</instance>
<instance id="com.arc.cdt.toolchain.arc.exeReleaseConfig.531153;com.arc.cdt.toolchain.arc.exeReleaseConfig.531153.1876446735;arc.cdt.toolchain.arc.exeCompilerRelease.270300290;com.arc.cdt.toolchain.arc.inputTypeCPP.858740852">
<collector id="org.eclipse.cdt.make.core.PerProjectSICollector">
<includePath path="C:\ARC\MetaWare\arc/inc"/>
<includePath path="C:\ARC\MetaWare\arc/incc"/>
<definedSymbol symbol="__HIGHC__"/>
<definedSymbol symbol="_GOC=1"/>
<definedSymbol symbol="_ARC=1"/>
<definedSymbol symbol="_ATT4=1"/>
<definedSymbol symbol="__HAS_LONGLONG=1"/>
<definedSymbol symbol="_ARCOMPACT=1"/>
<definedSymbol symbol="_ARCVER=0x21"/>
<definedSymbol symbol="__Xbarrel_shifter=1"/>
<definedSymbol symbol="_Interrupt1=_CC(_INTERRUPT1|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Interrupt2=_CC(_INTERRUPT2|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Exception=_CC(_EXCEPTION|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Preserve_flags=_CC(_PRESERVE_FLAGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Save_all_regs=_CC(_SAVE_ALL_REGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Never_returns=_CC(_NEVER_RETURNS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="__arc__=1"/>
<definedSymbol symbol="_ARC_LE=1"/>
<definedSymbol symbol="_LE=1"/>
<definedSymbol symbol="_REENTRANT=1"/>
<definedSymbol symbol="_MT=1"/>
</collector>
</instance>
<instance id="com.arc.cdt.toolchain.arc.exeReleaseConfig.531153;com.arc.cdt.toolchain.arc.exeReleaseConfig.531153.1876446735;arc.cdt.toolchain.arc.exeCompilerRelease.270300290;com.arc.cdt.toolchain.arc.inputTypeC.2023922365">
<collector id="org.eclipse.cdt.make.core.PerProjectSICollector">
<includePath path="C:\ARC\MetaWare\arc/inc"/>
<includePath path="C:\ARC\MetaWare\arc/incc"/>
<definedSymbol symbol="__HIGHC__"/>
<definedSymbol symbol="_GOC=1"/>
<definedSymbol symbol="_ARC=1"/>
<definedSymbol symbol="_ATT4=1"/>
<definedSymbol symbol="__HAS_LONGLONG=1"/>
<definedSymbol symbol="_ARCOMPACT=1"/>
<definedSymbol symbol="_ARCVER=0x21"/>
<definedSymbol symbol="__Xbarrel_shifter=1"/>
<definedSymbol symbol="_Interrupt1=_CC(_INTERRUPT1|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Interrupt2=_CC(_INTERRUPT2|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Exception=_CC(_EXCEPTION|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Preserve_flags=_CC(_PRESERVE_FLAGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Save_all_regs=_CC(_SAVE_ALL_REGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Never_returns=_CC(_NEVER_RETURNS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="__arc__=1"/>
<definedSymbol symbol="_ARC_LE=1"/>
<definedSymbol symbol="_LE=1"/>
<definedSymbol symbol="_REENTRANT=1"/>
<definedSymbol symbol="_MT=1"/>
</collector>
</instance>
</scannerInfo>
