<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?scdStore version="2"?>

<scannerInfo id="org.eclipse.cdt.make.core.discoveredScannerInfo">
<instance id="com.arc.cdt.toolchain.arc.exeDebugConfig.1967171072;com.arc.cdt.toolchain.arc.exeDebugConfig.1967171072.453309102;arc.exe.debug.exeCompilerDebug.606921162;com.arc.cdt.toolchain.arc.inputTypeC.249089192">
<collector id="org.eclipse.cdt.make.core.PerProjectSICollector">
<includePath path="C:\ARC\MetaWare\arc/inc"/>
<includePath path="C:\ARC\MetaWare\arc/incc"/>
<definedSymbol symbol="__HIGHC__"/>
<definedSymbol symbol="_GOC=1"/>
<definedSymbol symbol="_ARC=1"/>
<definedSymbol symbol="_ATT4=1"/>
<definedSymbol symbol="__HAS_LONGLONG=1"/>
<definedSymbol symbol="_ARCOMPACT=1"/>
<definedSymbol symbol="_ARCVER=0x21"/>
<definedSymbol symbol="__Xbarrel_shifter=1"/>
<definedSymbol symbol="_Interrupt1=_CC(_INTERRUPT1|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Interrupt2=_CC(_INTERRUPT2|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Exception=_CC(_EXCEPTION|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Preserve_flags=_CC(_PRESERVE_FLAGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Save_all_regs=_CC(_SAVE_ALL_REGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Never_returns=_CC(_NEVER_RETURNS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="__arc__=1"/>
<definedSymbol symbol="_ARC_LE=1"/>
<definedSymbol symbol="_LE=1"/>
<definedSymbol symbol="_REENTRANT=1"/>
<definedSymbol symbol="_MT=1"/>
</collector>
</instance>
<instance id="com.arc.cdt.toolchain.arc.exeDebugConfig.1967171072;com.arc.cdt.toolchain.arc.exeDebugConfig.1967171072.453309102;arc.exe.debug.exeCompilerDebug.606921162;com.arc.cdt.toolchain.arc.inputTypeCPP.1483412391">
<collector id="org.eclipse.cdt.make.core.PerProjectSICollector">
<includePath path="C:\ARC\MetaWare\arc/inc"/>
<includePath path="C:\ARC\MetaWare\arc/incc"/>
<definedSymbol symbol="__HIGHC__"/>
<definedSymbol symbol="_GOC=1"/>
<definedSymbol symbol="_ARC=1"/>
<definedSymbol symbol="_ATT4=1"/>
<definedSymbol symbol="__HAS_LONGLONG=1"/>
<definedSymbol symbol="_ARCOMPACT=1"/>
<definedSymbol symbol="_ARCVER=0x21"/>
<definedSymbol symbol="__Xbarrel_shifter=1"/>
<definedSymbol symbol="_Interrupt1=_CC(_INTERRUPT1|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Interrupt2=_CC(_INTERRUPT2|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Exception=_CC(_EXCEPTION|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Preserve_flags=_CC(_PRESERVE_FLAGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Save_all_regs=_CC(_SAVE_ALL_REGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Never_returns=_CC(_NEVER_RETURNS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="__arc__=1"/>
<definedSymbol symbol="_ARC_LE=1"/>
<definedSymbol symbol="_LE=1"/>
<definedSymbol symbol="_REENTRANT=1"/>
<definedSymbol symbol="_MT=1"/>
</collector>
</instance>
<instance id="com.arc.cdt.toolchain.arc.exeReleaseConfig.1486763645;com.arc.cdt.toolchain.arc.exeReleaseConfig.1486763645.22759296;arc.cdt.toolchain.arc.exeCompilerRelease.53202309;com.arc.cdt.toolchain.arc.inputTypeCPP.287638192">
<collector id="org.eclipse.cdt.make.core.PerProjectSICollector">
<includePath path="C:\ARC\MetaWare\arc/inc"/>
<includePath path="C:\ARC\MetaWare\arc/incc"/>
<definedSymbol symbol="__HIGHC__"/>
<definedSymbol symbol="_GOC=1"/>
<definedSymbol symbol="_ARC=1"/>
<definedSymbol symbol="_ATT4=1"/>
<definedSymbol symbol="__HAS_LONGLONG=1"/>
<definedSymbol symbol="_ARCOMPACT=1"/>
<definedSymbol symbol="_ARCVER=0x21"/>
<definedSymbol symbol="__Xbarrel_shifter=1"/>
<definedSymbol symbol="_Interrupt1=_CC(_INTERRUPT1|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Interrupt2=_CC(_INTERRUPT2|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Exception=_CC(_EXCEPTION|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Preserve_flags=_CC(_PRESERVE_FLAGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Save_all_regs=_CC(_SAVE_ALL_REGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Never_returns=_CC(_NEVER_RETURNS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="__arc__=1"/>
<definedSymbol symbol="_ARC_LE=1"/>
<definedSymbol symbol="_LE=1"/>
<definedSymbol symbol="_REENTRANT=1"/>
<definedSymbol symbol="_MT=1"/>
</collector>
</instance>
<instance id="com.arc.cdt.toolchain.arc.exeReleaseConfig.1486763645;com.arc.cdt.toolchain.arc.exeReleaseConfig.1486763645.22759296;arc.cdt.toolchain.arc.exeCompilerRelease.53202309;com.arc.cdt.toolchain.arc.inputTypeC.1062084629">
<collector id="org.eclipse.cdt.make.core.PerProjectSICollector">
<includePath path="C:\ARC\MetaWare\arc/inc"/>
<includePath path="C:\ARC\MetaWare\arc/incc"/>
<definedSymbol symbol="__HIGHC__"/>
<definedSymbol symbol="_GOC=1"/>
<definedSymbol symbol="_ARC=1"/>
<definedSymbol symbol="_ATT4=1"/>
<definedSymbol symbol="__HAS_LONGLONG=1"/>
<definedSymbol symbol="_ARCOMPACT=1"/>
<definedSymbol symbol="_ARCVER=0x21"/>
<definedSymbol symbol="__Xbarrel_shifter=1"/>
<definedSymbol symbol="_Interrupt1=_CC(_INTERRUPT1|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Interrupt2=_CC(_INTERRUPT2|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Exception=_CC(_EXCEPTION|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Preserve_flags=_CC(_PRESERVE_FLAGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Save_all_regs=_CC(_SAVE_ALL_REGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Never_returns=_CC(_NEVER_RETURNS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="__arc__=1"/>
<definedSymbol symbol="_ARC_LE=1"/>
<definedSymbol symbol="_LE=1"/>
<definedSymbol symbol="_REENTRANT=1"/>
<definedSymbol symbol="_MT=1"/>
</collector>
</instance>
<instance id="com.arc.cdt.toolchain.arc.exeDebugConfig.1967171072;com.arc.cdt.toolchain.arc.exeDebugConfig.1967171072.491331618;arc.exe.debug.exeCompilerDebug.606921162;com.arc.cdt.toolchain.arc.inputTypeCPP.248201761">
<collector id="org.eclipse.cdt.make.core.PerProjectSICollector">
<includePath path="C:\ARC\MetaWare\arc/inc"/>
<includePath path="C:\ARC\MetaWare\arc/incc"/>
<definedSymbol symbol="__HIGHC__"/>
<definedSymbol symbol="_GOC=1"/>
<definedSymbol symbol="_ARC=1"/>
<definedSymbol symbol="_ATT4=1"/>
<definedSymbol symbol="__HAS_LONGLONG=1"/>
<definedSymbol symbol="_ARCOMPACT=1"/>
<definedSymbol symbol="_ARCVER=0x21"/>
<definedSymbol symbol="__Xbarrel_shifter=1"/>
<definedSymbol symbol="_Interrupt1=_CC(_INTERRUPT1|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Interrupt2=_CC(_INTERRUPT2|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Exception=_CC(_EXCEPTION|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Preserve_flags=_CC(_PRESERVE_FLAGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Save_all_regs=_CC(_SAVE_ALL_REGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Never_returns=_CC(_NEVER_RETURNS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="__arc__=1"/>
<definedSymbol symbol="_ARC_LE=1"/>
<definedSymbol symbol="_LE=1"/>
<definedSymbol symbol="_REENTRANT=1"/>
<definedSymbol symbol="_MT=1"/>
</collector>
</instance>
<instance id="com.arc.cdt.toolchain.arc.exeDebugConfig.1967171072;com.arc.cdt.toolchain.arc.exeDebugConfig.1967171072.491331618;arc.exe.debug.exeCompilerDebug.606921162;com.arc.cdt.toolchain.arc.inputTypeC.1856060489">
<collector id="org.eclipse.cdt.make.core.PerProjectSICollector">
<includePath path="C:\ARC\MetaWare\arc/inc"/>
<includePath path="C:\ARC\MetaWare\arc/incc"/>
<definedSymbol symbol="__HIGHC__"/>
<definedSymbol symbol="_GOC=1"/>
<definedSymbol symbol="_ARC=1"/>
<definedSymbol symbol="_ATT4=1"/>
<definedSymbol symbol="__HAS_LONGLONG=1"/>
<definedSymbol symbol="_ARCOMPACT=1"/>
<definedSymbol symbol="_ARCVER=0x21"/>
<definedSymbol symbol="__Xbarrel_shifter=1"/>
<definedSymbol symbol="_Interrupt1=_CC(_INTERRUPT1|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Interrupt2=_CC(_INTERRUPT2|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Exception=_CC(_EXCEPTION|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Preserve_flags=_CC(_PRESERVE_FLAGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Save_all_regs=_CC(_SAVE_ALL_REGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Never_returns=_CC(_NEVER_RETURNS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="__arc__=1"/>
<definedSymbol symbol="_ARC_LE=1"/>
<definedSymbol symbol="_LE=1"/>
<definedSymbol symbol="_REENTRANT=1"/>
<definedSymbol symbol="_MT=1"/>
</collector>
</instance>
<instance id="com.arc.cdt.toolchain.arc.exeReleaseConfig.1486763645;com.arc.cdt.toolchain.arc.exeReleaseConfig.1486763645.269881135;arc.cdt.toolchain.arc.exeCompilerRelease.53202309;com.arc.cdt.toolchain.arc.inputTypeC.465318811">
<collector id="org.eclipse.cdt.make.core.PerProjectSICollector">
<includePath path="C:\ARC\MetaWare\arc/inc"/>
<includePath path="C:\ARC\MetaWare\arc/incc"/>
<definedSymbol symbol="__HIGHC__"/>
<definedSymbol symbol="_GOC=1"/>
<definedSymbol symbol="_ARC=1"/>
<definedSymbol symbol="_ATT4=1"/>
<definedSymbol symbol="__HAS_LONGLONG=1"/>
<definedSymbol symbol="_ARCOMPACT=1"/>
<definedSymbol symbol="_ARCVER=0x21"/>
<definedSymbol symbol="__Xbarrel_shifter=1"/>
<definedSymbol symbol="_Interrupt1=_CC(_INTERRUPT1|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Interrupt2=_CC(_INTERRUPT2|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Exception=_CC(_EXCEPTION|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Preserve_flags=_CC(_PRESERVE_FLAGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Save_all_regs=_CC(_SAVE_ALL_REGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Never_returns=_CC(_NEVER_RETURNS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="__arc__=1"/>
<definedSymbol symbol="_ARC_LE=1"/>
<definedSymbol symbol="_LE=1"/>
<definedSymbol symbol="_REENTRANT=1"/>
<definedSymbol symbol="_MT=1"/>
</collector>
</instance>
<instance id="com.arc.cdt.toolchain.arc.exeReleaseConfig.1486763645;com.arc.cdt.toolchain.arc.exeReleaseConfig.1486763645.269881135;arc.cdt.toolchain.arc.exeCompilerRelease.53202309;com.arc.cdt.toolchain.arc.inputTypeCPP.420416925">
<collector id="org.eclipse.cdt.make.core.PerProjectSICollector">
<includePath path="C:\ARC\MetaWare\arc/inc"/>
<includePath path="C:\ARC\MetaWare\arc/incc"/>
<definedSymbol symbol="__HIGHC__"/>
<definedSymbol symbol="_GOC=1"/>
<definedSymbol symbol="_ARC=1"/>
<definedSymbol symbol="_ATT4=1"/>
<definedSymbol symbol="__HAS_LONGLONG=1"/>
<definedSymbol symbol="_ARCOMPACT=1"/>
<definedSymbol symbol="_ARCVER=0x21"/>
<definedSymbol symbol="__Xbarrel_shifter=1"/>
<definedSymbol symbol="_Interrupt1=_CC(_INTERRUPT1|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Interrupt2=_CC(_INTERRUPT2|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Exception=_CC(_EXCEPTION|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Preserve_flags=_CC(_PRESERVE_FLAGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Save_all_regs=_CC(_SAVE_ALL_REGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Never_returns=_CC(_NEVER_RETURNS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="__arc__=1"/>
<definedSymbol symbol="_ARC_LE=1"/>
<definedSymbol symbol="_LE=1"/>
<definedSymbol symbol="_REENTRANT=1"/>
<definedSymbol symbol="_MT=1"/>
</collector>
</instance>
<instance id="com.arc.cdt.toolchain.arc.exeDebugConfig.1967171072;com.arc.cdt.toolchain.arc.exeDebugConfig.1967171072.663217928;arc.exe.debug.exeCompilerDebug.606921162;com.arc.cdt.toolchain.arc.inputTypeC.2134655883">
<collector id="org.eclipse.cdt.make.core.PerProjectSICollector">
<includePath path="C:\ARC\MetaWare\arc/inc"/>
<includePath path="C:\ARC\MetaWare\arc/incc"/>
<definedSymbol symbol="__HIGHC__"/>
<definedSymbol symbol="_GOC=1"/>
<definedSymbol symbol="_ARC=1"/>
<definedSymbol symbol="_ATT4=1"/>
<definedSymbol symbol="__HAS_LONGLONG=1"/>
<definedSymbol symbol="_ARCOMPACT=1"/>
<definedSymbol symbol="_ARCVER=0x21"/>
<definedSymbol symbol="__Xbarrel_shifter=1"/>
<definedSymbol symbol="_Interrupt1=_CC(_INTERRUPT1|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Interrupt2=_CC(_INTERRUPT2|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Exception=_CC(_EXCEPTION|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Preserve_flags=_CC(_PRESERVE_FLAGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Save_all_regs=_CC(_SAVE_ALL_REGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Never_returns=_CC(_NEVER_RETURNS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="__arc__=1"/>
<definedSymbol symbol="_ARC_LE=1"/>
<definedSymbol symbol="_LE=1"/>
<definedSymbol symbol="_REENTRANT=1"/>
<definedSymbol symbol="_MT=1"/>
</collector>
</instance>
<instance id="com.arc.cdt.toolchain.arc.exeDebugConfig.1967171072;com.arc.cdt.toolchain.arc.exeDebugConfig.1967171072.663217928;arc.exe.debug.exeCompilerDebug.606921162;com.arc.cdt.toolchain.arc.inputTypeCPP.899528537">
<collector id="org.eclipse.cdt.make.core.PerProjectSICollector">
<includePath path="C:\ARC\MetaWare\arc/inc"/>
<includePath path="C:\ARC\MetaWare\arc/incc"/>
<definedSymbol symbol="__HIGHC__"/>
<definedSymbol symbol="_GOC=1"/>
<definedSymbol symbol="_ARC=1"/>
<definedSymbol symbol="_ATT4=1"/>
<definedSymbol symbol="__HAS_LONGLONG=1"/>
<definedSymbol symbol="_ARCOMPACT=1"/>
<definedSymbol symbol="_ARCVER=0x21"/>
<definedSymbol symbol="__Xbarrel_shifter=1"/>
<definedSymbol symbol="_Interrupt1=_CC(_INTERRUPT1|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Interrupt2=_CC(_INTERRUPT2|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Exception=_CC(_EXCEPTION|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Preserve_flags=_CC(_PRESERVE_FLAGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Save_all_regs=_CC(_SAVE_ALL_REGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Never_returns=_CC(_NEVER_RETURNS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="__arc__=1"/>
<definedSymbol symbol="_ARC_LE=1"/>
<definedSymbol symbol="_LE=1"/>
<definedSymbol symbol="_REENTRANT=1"/>
<definedSymbol symbol="_MT=1"/>
</collector>
</instance>
<instance id="com.arc.cdt.toolchain.arc.exeReleaseConfig.1486763645;com.arc.cdt.toolchain.arc.exeReleaseConfig.1486763645.1175194283;arc.cdt.toolchain.arc.exeCompilerRelease.53202309;com.arc.cdt.toolchain.arc.inputTypeC.2062839644">
<collector id="org.eclipse.cdt.make.core.PerProjectSICollector">
<includePath path="C:\ARC\MetaWare\arc/inc"/>
<includePath path="C:\ARC\MetaWare\arc/incc"/>
<definedSymbol symbol="__HIGHC__"/>
<definedSymbol symbol="_GOC=1"/>
<definedSymbol symbol="_ARC=1"/>
<definedSymbol symbol="_ATT4=1"/>
<definedSymbol symbol="__HAS_LONGLONG=1"/>
<definedSymbol symbol="_ARCOMPACT=1"/>
<definedSymbol symbol="_ARCVER=0x21"/>
<definedSymbol symbol="__Xbarrel_shifter=1"/>
<definedSymbol symbol="_Interrupt1=_CC(_INTERRUPT1|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Interrupt2=_CC(_INTERRUPT2|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Exception=_CC(_EXCEPTION|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Preserve_flags=_CC(_PRESERVE_FLAGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Save_all_regs=_CC(_SAVE_ALL_REGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Never_returns=_CC(_NEVER_RETURNS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="__arc__=1"/>
<definedSymbol symbol="_ARC_LE=1"/>
<definedSymbol symbol="_LE=1"/>
<definedSymbol symbol="_REENTRANT=1"/>
<definedSymbol symbol="_MT=1"/>
</collector>
</instance>
<instance id="com.arc.cdt.toolchain.arc.exeReleaseConfig.1486763645;com.arc.cdt.toolchain.arc.exeReleaseConfig.1486763645.1175194283;arc.cdt.toolchain.arc.exeCompilerRelease.53202309;com.arc.cdt.toolchain.arc.inputTypeCPP.1321022179">
<collector id="org.eclipse.cdt.make.core.PerProjectSICollector">
<includePath path="C:\ARC\MetaWare\arc/inc"/>
<includePath path="C:\ARC\MetaWare\arc/incc"/>
<definedSymbol symbol="__HIGHC__"/>
<definedSymbol symbol="_GOC=1"/>
<definedSymbol symbol="_ARC=1"/>
<definedSymbol symbol="_ATT4=1"/>
<definedSymbol symbol="__HAS_LONGLONG=1"/>
<definedSymbol symbol="_ARCOMPACT=1"/>
<definedSymbol symbol="_ARCVER=0x21"/>
<definedSymbol symbol="__Xbarrel_shifter=1"/>
<definedSymbol symbol="_Interrupt1=_CC(_INTERRUPT1|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Interrupt2=_CC(_INTERRUPT2|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Exception=_CC(_EXCEPTION|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Preserve_flags=_CC(_PRESERVE_FLAGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Save_all_regs=_CC(_SAVE_ALL_REGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Never_returns=_CC(_NEVER_RETURNS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="__arc__=1"/>
<definedSymbol symbol="_ARC_LE=1"/>
<definedSymbol symbol="_LE=1"/>
<definedSymbol symbol="_REENTRANT=1"/>
<definedSymbol symbol="_MT=1"/>
</collector>
</instance>
<instance id="com.arc.cdt.toolchain.arc.exeDebugConfig.1967171072;com.arc.cdt.toolchain.arc.exeDebugConfig.1967171072.1267891864;arc.exe.debug.exeCompilerDebug.606921162;com.arc.cdt.toolchain.arc.inputTypeCPP.42775457">
<collector id="org.eclipse.cdt.make.core.PerProjectSICollector">
<includePath path="C:\ARC\MetaWare\arc/inc"/>
<includePath path="C:\ARC\MetaWare\arc/incc"/>
<definedSymbol symbol="__HIGHC__"/>
<definedSymbol symbol="_GOC=1"/>
<definedSymbol symbol="_ARC=1"/>
<definedSymbol symbol="_ATT4=1"/>
<definedSymbol symbol="__HAS_LONGLONG=1"/>
<definedSymbol symbol="_ARCOMPACT=1"/>
<definedSymbol symbol="_ARCVER=0x21"/>
<definedSymbol symbol="__Xbarrel_shifter=1"/>
<definedSymbol symbol="_Interrupt1=_CC(_INTERRUPT1|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Interrupt2=_CC(_INTERRUPT2|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Exception=_CC(_EXCEPTION|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Preserve_flags=_CC(_PRESERVE_FLAGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Save_all_regs=_CC(_SAVE_ALL_REGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Never_returns=_CC(_NEVER_RETURNS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="__arc__=1"/>
<definedSymbol symbol="_ARC_LE=1"/>
<definedSymbol symbol="_LE=1"/>
<definedSymbol symbol="_REENTRANT=1"/>
<definedSymbol symbol="_MT=1"/>
</collector>
</instance>
<instance id="com.arc.cdt.toolchain.arc.exeDebugConfig.1967171072;com.arc.cdt.toolchain.arc.exeDebugConfig.1967171072.1267891864;arc.exe.debug.exeCompilerDebug.606921162;com.arc.cdt.toolchain.arc.inputTypeC.746016903">
<collector id="org.eclipse.cdt.make.core.PerProjectSICollector">
<includePath path="C:\ARC\MetaWare\arc/inc"/>
<includePath path="C:\ARC\MetaWare\arc/incc"/>
<definedSymbol symbol="__HIGHC__"/>
<definedSymbol symbol="_GOC=1"/>
<definedSymbol symbol="_ARC=1"/>
<definedSymbol symbol="_ATT4=1"/>
<definedSymbol symbol="__HAS_LONGLONG=1"/>
<definedSymbol symbol="_ARCOMPACT=1"/>
<definedSymbol symbol="_ARCVER=0x21"/>
<definedSymbol symbol="__Xbarrel_shifter=1"/>
<definedSymbol symbol="_Interrupt1=_CC(_INTERRUPT1|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Interrupt2=_CC(_INTERRUPT2|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Exception=_CC(_EXCEPTION|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Preserve_flags=_CC(_PRESERVE_FLAGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Save_all_regs=_CC(_SAVE_ALL_REGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Never_returns=_CC(_NEVER_RETURNS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="__arc__=1"/>
<definedSymbol symbol="_ARC_LE=1"/>
<definedSymbol symbol="_LE=1"/>
<definedSymbol symbol="_REENTRANT=1"/>
<definedSymbol symbol="_MT=1"/>
</collector>
</instance>
<instance id="com.arc.cdt.toolchain.arc.exeReleaseConfig.1486763645;com.arc.cdt.toolchain.arc.exeReleaseConfig.1486763645.617253699;arc.cdt.toolchain.arc.exeCompilerRelease.53202309;com.arc.cdt.toolchain.arc.inputTypeCPP.1780791928">
<collector id="org.eclipse.cdt.make.core.PerProjectSICollector">
<includePath path="C:\ARC\MetaWare\arc/inc"/>
<includePath path="C:\ARC\MetaWare\arc/incc"/>
<definedSymbol symbol="__HIGHC__"/>
<definedSymbol symbol="_GOC=1"/>
<definedSymbol symbol="_ARC=1"/>
<definedSymbol symbol="_ATT4=1"/>
<definedSymbol symbol="__HAS_LONGLONG=1"/>
<definedSymbol symbol="_ARCOMPACT=1"/>
<definedSymbol symbol="_ARCVER=0x21"/>
<definedSymbol symbol="__Xbarrel_shifter=1"/>
<definedSymbol symbol="_Interrupt1=_CC(_INTERRUPT1|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Interrupt2=_CC(_INTERRUPT2|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Exception=_CC(_EXCEPTION|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Preserve_flags=_CC(_PRESERVE_FLAGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Save_all_regs=_CC(_SAVE_ALL_REGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Never_returns=_CC(_NEVER_RETURNS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="__arc__=1"/>
<definedSymbol symbol="_ARC_LE=1"/>
<definedSymbol symbol="_LE=1"/>
<definedSymbol symbol="_REENTRANT=1"/>
<definedSymbol symbol="_MT=1"/>
</collector>
</instance>
<instance id="com.arc.cdt.toolchain.arc.exeReleaseConfig.1486763645;com.arc.cdt.toolchain.arc.exeReleaseConfig.1486763645.617253699;arc.cdt.toolchain.arc.exeCompilerRelease.53202309;com.arc.cdt.toolchain.arc.inputTypeC.231692996">
<collector id="org.eclipse.cdt.make.core.PerProjectSICollector">
<includePath path="C:\ARC\MetaWare\arc/inc"/>
<includePath path="C:\ARC\MetaWare\arc/incc"/>
<definedSymbol symbol="__HIGHC__"/>
<definedSymbol symbol="_GOC=1"/>
<definedSymbol symbol="_ARC=1"/>
<definedSymbol symbol="_ATT4=1"/>
<definedSymbol symbol="__HAS_LONGLONG=1"/>
<definedSymbol symbol="_ARCOMPACT=1"/>
<definedSymbol symbol="_ARCVER=0x21"/>
<definedSymbol symbol="__Xbarrel_shifter=1"/>
<definedSymbol symbol="_Interrupt1=_CC(_INTERRUPT1|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Interrupt2=_CC(_INTERRUPT2|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Exception=_CC(_EXCEPTION|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Preserve_flags=_CC(_PRESERVE_FLAGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Save_all_regs=_CC(_SAVE_ALL_REGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Never_returns=_CC(_NEVER_RETURNS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="__arc__=1"/>
<definedSymbol symbol="_ARC_LE=1"/>
<definedSymbol symbol="_LE=1"/>
<definedSymbol symbol="_REENTRANT=1"/>
<definedSymbol symbol="_MT=1"/>
</collector>
</instance>
<instance id="com.arc.cdt.toolchain.arc.exeDebugConfig.1967171072;com.arc.cdt.toolchain.arc.exeDebugConfig.1967171072.17612308;arc.exe.debug.exeCompilerDebug.606921162;com.arc.cdt.toolchain.arc.inputTypeCPP.756097938">
<collector id="org.eclipse.cdt.make.core.PerProjectSICollector">
<includePath path="C:\ARC\MetaWare\arc/inc"/>
<includePath path="C:\ARC\MetaWare\arc/incc"/>
<definedSymbol symbol="__HIGHC__"/>
<definedSymbol symbol="_GOC=1"/>
<definedSymbol symbol="_ARC=1"/>
<definedSymbol symbol="_ATT4=1"/>
<definedSymbol symbol="__HAS_LONGLONG=1"/>
<definedSymbol symbol="_ARCOMPACT=1"/>
<definedSymbol symbol="_ARCVER=0x21"/>
<definedSymbol symbol="__Xbarrel_shifter=1"/>
<definedSymbol symbol="_Interrupt1=_CC(_INTERRUPT1|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Interrupt2=_CC(_INTERRUPT2|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Exception=_CC(_EXCEPTION|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Preserve_flags=_CC(_PRESERVE_FLAGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Save_all_regs=_CC(_SAVE_ALL_REGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Never_returns=_CC(_NEVER_RETURNS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="__arc__=1"/>
<definedSymbol symbol="_ARC_LE=1"/>
<definedSymbol symbol="_LE=1"/>
<definedSymbol symbol="_REENTRANT=1"/>
<definedSymbol symbol="_MT=1"/>
</collector>
</instance>
<instance id="com.arc.cdt.toolchain.arc.exeDebugConfig.1967171072;com.arc.cdt.toolchain.arc.exeDebugConfig.1967171072.17612308;arc.exe.debug.exeCompilerDebug.606921162;com.arc.cdt.toolchain.arc.inputTypeC.412961096">
<collector id="org.eclipse.cdt.make.core.PerProjectSICollector">
<includePath path="C:\ARC\MetaWare\arc/inc"/>
<includePath path="C:\ARC\MetaWare\arc/incc"/>
<definedSymbol symbol="__HIGHC__"/>
<definedSymbol symbol="_GOC=1"/>
<definedSymbol symbol="_ARC=1"/>
<definedSymbol symbol="_ATT4=1"/>
<definedSymbol symbol="__HAS_LONGLONG=1"/>
<definedSymbol symbol="_ARCOMPACT=1"/>
<definedSymbol symbol="_ARCVER=0x21"/>
<definedSymbol symbol="__Xbarrel_shifter=1"/>
<definedSymbol symbol="_Interrupt1=_CC(_INTERRUPT1|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Interrupt2=_CC(_INTERRUPT2|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Exception=_CC(_EXCEPTION|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Preserve_flags=_CC(_PRESERVE_FLAGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Save_all_regs=_CC(_SAVE_ALL_REGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Never_returns=_CC(_NEVER_RETURNS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="__arc__=1"/>
<definedSymbol symbol="_ARC_LE=1"/>
<definedSymbol symbol="_LE=1"/>
<definedSymbol symbol="_REENTRANT=1"/>
<definedSymbol symbol="_MT=1"/>
</collector>
</instance>
<instance id="com.arc.cdt.toolchain.arc.exeReleaseConfig.1486763645;com.arc.cdt.toolchain.arc.exeReleaseConfig.1486763645.149337712;arc.cdt.toolchain.arc.exeCompilerRelease.53202309;com.arc.cdt.toolchain.arc.inputTypeC.941565191">
<collector id="org.eclipse.cdt.make.core.PerProjectSICollector">
<includePath path="C:\ARC\MetaWare\arc/inc"/>
<includePath path="C:\ARC\MetaWare\arc/incc"/>
<definedSymbol symbol="__HIGHC__"/>
<definedSymbol symbol="_GOC=1"/>
<definedSymbol symbol="_ARC=1"/>
<definedSymbol symbol="_ATT4=1"/>
<definedSymbol symbol="__HAS_LONGLONG=1"/>
<definedSymbol symbol="_ARCOMPACT=1"/>
<definedSymbol symbol="_ARCVER=0x21"/>
<definedSymbol symbol="__Xbarrel_shifter=1"/>
<definedSymbol symbol="_Interrupt1=_CC(_INTERRUPT1|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Interrupt2=_CC(_INTERRUPT2|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Exception=_CC(_EXCEPTION|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Preserve_flags=_CC(_PRESERVE_FLAGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Save_all_regs=_CC(_SAVE_ALL_REGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Never_returns=_CC(_NEVER_RETURNS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="__arc__=1"/>
<definedSymbol symbol="_ARC_LE=1"/>
<definedSymbol symbol="_LE=1"/>
<definedSymbol symbol="_REENTRANT=1"/>
<definedSymbol symbol="_MT=1"/>
</collector>
</instance>
<instance id="com.arc.cdt.toolchain.arc.exeReleaseConfig.1486763645;com.arc.cdt.toolchain.arc.exeReleaseConfig.1486763645.149337712;arc.cdt.toolchain.arc.exeCompilerRelease.53202309;com.arc.cdt.toolchain.arc.inputTypeCPP.276554094">
<collector id="org.eclipse.cdt.make.core.PerProjectSICollector">
<includePath path="C:\ARC\MetaWare\arc/inc"/>
<includePath path="C:\ARC\MetaWare\arc/incc"/>
<definedSymbol symbol="__HIGHC__"/>
<definedSymbol symbol="_GOC=1"/>
<definedSymbol symbol="_ARC=1"/>
<definedSymbol symbol="_ATT4=1"/>
<definedSymbol symbol="__HAS_LONGLONG=1"/>
<definedSymbol symbol="_ARCOMPACT=1"/>
<definedSymbol symbol="_ARCVER=0x21"/>
<definedSymbol symbol="__Xbarrel_shifter=1"/>
<definedSymbol symbol="_Interrupt1=_CC(_INTERRUPT1|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Interrupt2=_CC(_INTERRUPT2|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Exception=_CC(_EXCEPTION|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Preserve_flags=_CC(_PRESERVE_FLAGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Save_all_regs=_CC(_SAVE_ALL_REGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Never_returns=_CC(_NEVER_RETURNS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="__arc__=1"/>
<definedSymbol symbol="_ARC_LE=1"/>
<definedSymbol symbol="_LE=1"/>
<definedSymbol symbol="_REENTRANT=1"/>
<definedSymbol symbol="_MT=1"/>
</collector>
</instance>
<instance id="com.arc.cdt.toolchain.arc.exeDebugConfig.1967171072;com.arc.cdt.toolchain.arc.exeDebugConfig.1967171072.17612308;arc.exe.debug.exeCompilerDebug.606921162;com.arc.cdt.toolchain.arc.inputTypeC.661670778">
<collector id="org.eclipse.cdt.make.core.PerProjectSICollector">
<includePath path="C:\ARC\MetaWare\arc/inc"/>
<includePath path="C:\ARC\MetaWare\arc/incc"/>
<definedSymbol symbol="__HIGHC__"/>
<definedSymbol symbol="_GOC=1"/>
<definedSymbol symbol="_ARC=1"/>
<definedSymbol symbol="_ATT4=1"/>
<definedSymbol symbol="__HAS_LONGLONG=1"/>
<definedSymbol symbol="_ARCOMPACT=1"/>
<definedSymbol symbol="_ARCVER=0x21"/>
<definedSymbol symbol="__Xbarrel_shifter=1"/>
<definedSymbol symbol="_Interrupt1=_CC(_INTERRUPT1|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Interrupt2=_CC(_INTERRUPT2|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Exception=_CC(_EXCEPTION|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Preserve_flags=_CC(_PRESERVE_FLAGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Save_all_regs=_CC(_SAVE_ALL_REGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Never_returns=_CC(_NEVER_RETURNS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="__arc__=1"/>
<definedSymbol symbol="_ARC_LE=1"/>
<definedSymbol symbol="_LE=1"/>
<definedSymbol symbol="_REENTRANT=1"/>
<definedSymbol symbol="_MT=1"/>
</collector>
</instance>
<instance id="com.arc.cdt.toolchain.arc.exeDebugConfig.1967171072;com.arc.cdt.toolchain.arc.exeDebugConfig.1967171072.17612308;arc.exe.debug.exeCompilerDebug.606921162;com.arc.cdt.toolchain.arc.inputTypeCPP.1850740553">
<collector id="org.eclipse.cdt.make.core.PerProjectSICollector">
<includePath path="C:\ARC\MetaWare\arc/inc"/>
<includePath path="C:\ARC\MetaWare\arc/incc"/>
<definedSymbol symbol="__HIGHC__"/>
<definedSymbol symbol="_GOC=1"/>
<definedSymbol symbol="_ARC=1"/>
<definedSymbol symbol="_ATT4=1"/>
<definedSymbol symbol="__HAS_LONGLONG=1"/>
<definedSymbol symbol="_ARCOMPACT=1"/>
<definedSymbol symbol="_ARCVER=0x21"/>
<definedSymbol symbol="__Xbarrel_shifter=1"/>
<definedSymbol symbol="_Interrupt1=_CC(_INTERRUPT1|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Interrupt2=_CC(_INTERRUPT2|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Exception=_CC(_EXCEPTION|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Preserve_flags=_CC(_PRESERVE_FLAGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Save_all_regs=_CC(_SAVE_ALL_REGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Never_returns=_CC(_NEVER_RETURNS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="__arc__=1"/>
<definedSymbol symbol="_ARC_LE=1"/>
<definedSymbol symbol="_LE=1"/>
<definedSymbol symbol="_REENTRANT=1"/>
<definedSymbol symbol="_MT=1"/>
</collector>
</instance>
<instance id="com.arc.cdt.toolchain.arc.exeReleaseConfig.1486763645;com.arc.cdt.toolchain.arc.exeReleaseConfig.1486763645.149337712;arc.cdt.toolchain.arc.exeCompilerRelease.53202309;com.arc.cdt.toolchain.arc.inputTypeC.70533688">
<collector id="org.eclipse.cdt.make.core.PerProjectSICollector">
<includePath path="C:\ARC\MetaWare\arc/inc"/>
<includePath path="C:\ARC\MetaWare\arc/incc"/>
<definedSymbol symbol="__HIGHC__"/>
<definedSymbol symbol="_GOC=1"/>
<definedSymbol symbol="_ARC=1"/>
<definedSymbol symbol="_ATT4=1"/>
<definedSymbol symbol="__HAS_LONGLONG=1"/>
<definedSymbol symbol="_ARCOMPACT=1"/>
<definedSymbol symbol="_ARCVER=0x21"/>
<definedSymbol symbol="__Xbarrel_shifter=1"/>
<definedSymbol symbol="_Interrupt1=_CC(_INTERRUPT1|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Interrupt2=_CC(_INTERRUPT2|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Exception=_CC(_EXCEPTION|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Preserve_flags=_CC(_PRESERVE_FLAGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Save_all_regs=_CC(_SAVE_ALL_REGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Never_returns=_CC(_NEVER_RETURNS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="__arc__=1"/>
<definedSymbol symbol="_ARC_LE=1"/>
<definedSymbol symbol="_LE=1"/>
<definedSymbol symbol="_REENTRANT=1"/>
<definedSymbol symbol="_MT=1"/>
</collector>
</instance>
<instance id="com.arc.cdt.toolchain.arc.exeReleaseConfig.1486763645;com.arc.cdt.toolchain.arc.exeReleaseConfig.1486763645.149337712;arc.cdt.toolchain.arc.exeCompilerRelease.53202309;com.arc.cdt.toolchain.arc.inputTypeCPP.1409613298">
<collector id="org.eclipse.cdt.make.core.PerProjectSICollector">
<includePath path="C:\ARC\MetaWare\arc/inc"/>
<includePath path="C:\ARC\MetaWare\arc/incc"/>
<definedSymbol symbol="__HIGHC__"/>
<definedSymbol symbol="_GOC=1"/>
<definedSymbol symbol="_ARC=1"/>
<definedSymbol symbol="_ATT4=1"/>
<definedSymbol symbol="__HAS_LONGLONG=1"/>
<definedSymbol symbol="_ARCOMPACT=1"/>
<definedSymbol symbol="_ARCVER=0x21"/>
<definedSymbol symbol="__Xbarrel_shifter=1"/>
<definedSymbol symbol="_Interrupt1=_CC(_INTERRUPT1|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Interrupt2=_CC(_INTERRUPT2|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Exception=_CC(_EXCEPTION|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Preserve_flags=_CC(_PRESERVE_FLAGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Save_all_regs=_CC(_SAVE_ALL_REGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Never_returns=_CC(_NEVER_RETURNS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="__arc__=1"/>
<definedSymbol symbol="_ARC_LE=1"/>
<definedSymbol symbol="_LE=1"/>
<definedSymbol symbol="_REENTRANT=1"/>
<definedSymbol symbol="_MT=1"/>
</collector>
</instance>
<instance id="com.arc.cdt.toolchain.arc.exeDebugConfig.1967171072;com.arc.cdt.toolchain.arc.exeDebugConfig.1967171072.17612308;arc.exe.debug.exeCompilerDebug.606921162;com.arc.cdt.toolchain.arc.inputTypeCPP.445944863">
<collector id="org.eclipse.cdt.make.core.PerProjectSICollector">
<includePath path="C:\ARC\MetaWare\arc/inc"/>
<includePath path="C:\ARC\MetaWare\arc/incc"/>
<definedSymbol symbol="__HIGHC__"/>
<definedSymbol symbol="_GOC=1"/>
<definedSymbol symbol="_ARC=1"/>
<definedSymbol symbol="_ATT4=1"/>
<definedSymbol symbol="__HAS_LONGLONG=1"/>
<definedSymbol symbol="_ARCOMPACT=1"/>
<definedSymbol symbol="_ARCVER=0x21"/>
<definedSymbol symbol="__Xbarrel_shifter=1"/>
<definedSymbol symbol="_Interrupt1=_CC(_INTERRUPT1|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Interrupt2=_CC(_INTERRUPT2|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Exception=_CC(_EXCEPTION|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Preserve_flags=_CC(_PRESERVE_FLAGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Save_all_regs=_CC(_SAVE_ALL_REGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Never_returns=_CC(_NEVER_RETURNS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="__arc__=1"/>
<definedSymbol symbol="_ARC_LE=1"/>
<definedSymbol symbol="_LE=1"/>
<definedSymbol symbol="_REENTRANT=1"/>
<definedSymbol symbol="_MT=1"/>
</collector>
</instance>
<instance id="com.arc.cdt.toolchain.arc.exeDebugConfig.1967171072;com.arc.cdt.toolchain.arc.exeDebugConfig.1967171072.17612308;arc.exe.debug.exeCompilerDebug.606921162;com.arc.cdt.toolchain.arc.inputTypeC.1458333847">
<collector id="org.eclipse.cdt.make.core.PerProjectSICollector">
<includePath path="C:\ARC\MetaWare\arc/inc"/>
<includePath path="C:\ARC\MetaWare\arc/incc"/>
<definedSymbol symbol="__HIGHC__"/>
<definedSymbol symbol="_GOC=1"/>
<definedSymbol symbol="_ARC=1"/>
<definedSymbol symbol="_ATT4=1"/>
<definedSymbol symbol="__HAS_LONGLONG=1"/>
<definedSymbol symbol="_ARCOMPACT=1"/>
<definedSymbol symbol="_ARCVER=0x21"/>
<definedSymbol symbol="__Xbarrel_shifter=1"/>
<definedSymbol symbol="_Interrupt1=_CC(_INTERRUPT1|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Interrupt2=_CC(_INTERRUPT2|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Exception=_CC(_EXCEPTION|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Preserve_flags=_CC(_PRESERVE_FLAGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Save_all_regs=_CC(_SAVE_ALL_REGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Never_returns=_CC(_NEVER_RETURNS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="__arc__=1"/>
<definedSymbol symbol="_ARC_LE=1"/>
<definedSymbol symbol="_LE=1"/>
<definedSymbol symbol="_REENTRANT=1"/>
<definedSymbol symbol="_MT=1"/>
</collector>
</instance>
<instance id="com.arc.cdt.toolchain.arc.exeReleaseConfig.1486763645;com.arc.cdt.toolchain.arc.exeReleaseConfig.1486763645.149337712;arc.cdt.toolchain.arc.exeCompilerRelease.53202309;com.arc.cdt.toolchain.arc.inputTypeC.2123648672">
<collector id="org.eclipse.cdt.make.core.PerProjectSICollector">
<includePath path="C:\ARC\MetaWare\arc/inc"/>
<includePath path="C:\ARC\MetaWare\arc/incc"/>
<definedSymbol symbol="__HIGHC__"/>
<definedSymbol symbol="_GOC=1"/>
<definedSymbol symbol="_ARC=1"/>
<definedSymbol symbol="_ATT4=1"/>
<definedSymbol symbol="__HAS_LONGLONG=1"/>
<definedSymbol symbol="_ARCOMPACT=1"/>
<definedSymbol symbol="_ARCVER=0x21"/>
<definedSymbol symbol="__Xbarrel_shifter=1"/>
<definedSymbol symbol="_Interrupt1=_CC(_INTERRUPT1|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Interrupt2=_CC(_INTERRUPT2|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Exception=_CC(_EXCEPTION|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Preserve_flags=_CC(_PRESERVE_FLAGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Save_all_regs=_CC(_SAVE_ALL_REGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Never_returns=_CC(_NEVER_RETURNS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="__arc__=1"/>
<definedSymbol symbol="_ARC_LE=1"/>
<definedSymbol symbol="_LE=1"/>
<definedSymbol symbol="_REENTRANT=1"/>
<definedSymbol symbol="_MT=1"/>
</collector>
</instance>
<instance id="com.arc.cdt.toolchain.arc.exeReleaseConfig.1486763645;com.arc.cdt.toolchain.arc.exeReleaseConfig.1486763645.149337712;arc.cdt.toolchain.arc.exeCompilerRelease.53202309;com.arc.cdt.toolchain.arc.inputTypeCPP.1560596">
<collector id="org.eclipse.cdt.make.core.PerProjectSICollector">
<includePath path="C:\ARC\MetaWare\arc/inc"/>
<includePath path="C:\ARC\MetaWare\arc/incc"/>
<definedSymbol symbol="__HIGHC__"/>
<definedSymbol symbol="_GOC=1"/>
<definedSymbol symbol="_ARC=1"/>
<definedSymbol symbol="_ATT4=1"/>
<definedSymbol symbol="__HAS_LONGLONG=1"/>
<definedSymbol symbol="_ARCOMPACT=1"/>
<definedSymbol symbol="_ARCVER=0x21"/>
<definedSymbol symbol="__Xbarrel_shifter=1"/>
<definedSymbol symbol="_Interrupt1=_CC(_INTERRUPT1|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Interrupt2=_CC(_INTERRUPT2|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Exception=_CC(_EXCEPTION|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Preserve_flags=_CC(_PRESERVE_FLAGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Save_all_regs=_CC(_SAVE_ALL_REGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Never_returns=_CC(_NEVER_RETURNS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="__arc__=1"/>
<definedSymbol symbol="_ARC_LE=1"/>
<definedSymbol symbol="_LE=1"/>
<definedSymbol symbol="_REENTRANT=1"/>
<definedSymbol symbol="_MT=1"/>
</collector>
</instance>
<instance id="com.arc.cdt.toolchain.arc.exeDebugConfig.1967171072;com.arc.cdt.toolchain.arc.exeDebugConfig.1967171072.17612308;arc.exe.debug.exeCompilerDebug.606921162;com.arc.cdt.toolchain.arc.inputTypeCPP.997170950">
<collector id="org.eclipse.cdt.make.core.PerProjectSICollector">
<includePath path="C:\ARC\MetaWare\arc/inc"/>
<includePath path="C:\ARC\MetaWare\arc/incc"/>
<definedSymbol symbol="__HIGHC__"/>
<definedSymbol symbol="_GOC=1"/>
<definedSymbol symbol="_ARC=1"/>
<definedSymbol symbol="_ATT4=1"/>
<definedSymbol symbol="__HAS_LONGLONG=1"/>
<definedSymbol symbol="_ARCOMPACT=1"/>
<definedSymbol symbol="_ARCVER=0x21"/>
<definedSymbol symbol="__Xbarrel_shifter=1"/>
<definedSymbol symbol="_Interrupt1=_CC(_INTERRUPT1|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Interrupt2=_CC(_INTERRUPT2|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Exception=_CC(_EXCEPTION|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Preserve_flags=_CC(_PRESERVE_FLAGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Save_all_regs=_CC(_SAVE_ALL_REGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Never_returns=_CC(_NEVER_RETURNS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="__arc__=1"/>
<definedSymbol symbol="_ARC_LE=1"/>
<definedSymbol symbol="_LE=1"/>
<definedSymbol symbol="_REENTRANT=1"/>
<definedSymbol symbol="_MT=1"/>
</collector>
</instance>
<instance id="com.arc.cdt.toolchain.arc.exeDebugConfig.1967171072;com.arc.cdt.toolchain.arc.exeDebugConfig.1967171072.17612308;arc.exe.debug.exeCompilerDebug.606921162;com.arc.cdt.toolchain.arc.inputTypeC.216613803">
<collector id="org.eclipse.cdt.make.core.PerProjectSICollector">
<includePath path="C:\ARC\MetaWare\arc/inc"/>
<includePath path="C:\ARC\MetaWare\arc/incc"/>
<definedSymbol symbol="__HIGHC__"/>
<definedSymbol symbol="_GOC=1"/>
<definedSymbol symbol="_ARC=1"/>
<definedSymbol symbol="_ATT4=1"/>
<definedSymbol symbol="__HAS_LONGLONG=1"/>
<definedSymbol symbol="_ARCOMPACT=1"/>
<definedSymbol symbol="_ARCVER=0x21"/>
<definedSymbol symbol="__Xbarrel_shifter=1"/>
<definedSymbol symbol="_Interrupt1=_CC(_INTERRUPT1|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Interrupt2=_CC(_INTERRUPT2|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Exception=_CC(_EXCEPTION|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Preserve_flags=_CC(_PRESERVE_FLAGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Save_all_regs=_CC(_SAVE_ALL_REGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Never_returns=_CC(_NEVER_RETURNS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="__arc__=1"/>
<definedSymbol symbol="_ARC_LE=1"/>
<definedSymbol symbol="_LE=1"/>
<definedSymbol symbol="_REENTRANT=1"/>
<definedSymbol symbol="_MT=1"/>
</collector>
</instance>
<instance id="com.arc.cdt.toolchain.arc.exeReleaseConfig.1486763645;com.arc.cdt.toolchain.arc.exeReleaseConfig.1486763645.149337712;arc.cdt.toolchain.arc.exeCompilerRelease.53202309;com.arc.cdt.toolchain.arc.inputTypeC.1905997895">
<collector id="org.eclipse.cdt.make.core.PerProjectSICollector">
<includePath path="C:\ARC\MetaWare\arc/inc"/>
<includePath path="C:\ARC\MetaWare\arc/incc"/>
<definedSymbol symbol="__HIGHC__"/>
<definedSymbol symbol="_GOC=1"/>
<definedSymbol symbol="_ARC=1"/>
<definedSymbol symbol="_ATT4=1"/>
<definedSymbol symbol="__HAS_LONGLONG=1"/>
<definedSymbol symbol="_ARCOMPACT=1"/>
<definedSymbol symbol="_ARCVER=0x21"/>
<definedSymbol symbol="__Xbarrel_shifter=1"/>
<definedSymbol symbol="_Interrupt1=_CC(_INTERRUPT1|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Interrupt2=_CC(_INTERRUPT2|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Exception=_CC(_EXCEPTION|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Preserve_flags=_CC(_PRESERVE_FLAGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Save_all_regs=_CC(_SAVE_ALL_REGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Never_returns=_CC(_NEVER_RETURNS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="__arc__=1"/>
<definedSymbol symbol="_ARC_LE=1"/>
<definedSymbol symbol="_LE=1"/>
<definedSymbol symbol="_REENTRANT=1"/>
<definedSymbol symbol="_MT=1"/>
</collector>
</instance>
<instance id="com.arc.cdt.toolchain.arc.exeReleaseConfig.1486763645;com.arc.cdt.toolchain.arc.exeReleaseConfig.1486763645.149337712;arc.cdt.toolchain.arc.exeCompilerRelease.53202309;com.arc.cdt.toolchain.arc.inputTypeCPP.376404884">
<collector id="org.eclipse.cdt.make.core.PerProjectSICollector">
<includePath path="C:\ARC\MetaWare\arc/inc"/>
<includePath path="C:\ARC\MetaWare\arc/incc"/>
<definedSymbol symbol="__HIGHC__"/>
<definedSymbol symbol="_GOC=1"/>
<definedSymbol symbol="_ARC=1"/>
<definedSymbol symbol="_ATT4=1"/>
<definedSymbol symbol="__HAS_LONGLONG=1"/>
<definedSymbol symbol="_ARCOMPACT=1"/>
<definedSymbol symbol="_ARCVER=0x21"/>
<definedSymbol symbol="__Xbarrel_shifter=1"/>
<definedSymbol symbol="_Interrupt1=_CC(_INTERRUPT1|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Interrupt2=_CC(_INTERRUPT2|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Exception=_CC(_EXCEPTION|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Preserve_flags=_CC(_PRESERVE_FLAGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Save_all_regs=_CC(_SAVE_ALL_REGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Never_returns=_CC(_NEVER_RETURNS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="__arc__=1"/>
<definedSymbol symbol="_ARC_LE=1"/>
<definedSymbol symbol="_LE=1"/>
<definedSymbol symbol="_REENTRANT=1"/>
<definedSymbol symbol="_MT=1"/>
</collector>
</instance>
<instance id="com.arc.cdt.toolchain.arc.exeDebugConfig.1967171072;com.arc.cdt.toolchain.arc.exeDebugConfig.1967171072.1595001667;arc.exe.debug.exeCompilerDebug.606921162;com.arc.cdt.toolchain.arc.inputTypeC.1436780967">
<collector id="org.eclipse.cdt.make.core.PerProjectSICollector">
<includePath path="C:\ARC\MetaWare\arc/inc"/>
<includePath path="C:\ARC\MetaWare\arc/incc"/>
<definedSymbol symbol="__HIGHC__"/>
<definedSymbol symbol="_GOC=1"/>
<definedSymbol symbol="_ARC=1"/>
<definedSymbol symbol="_ATT4=1"/>
<definedSymbol symbol="__HAS_LONGLONG=1"/>
<definedSymbol symbol="_ARCOMPACT=1"/>
<definedSymbol symbol="_ARCVER=0x21"/>
<definedSymbol symbol="__Xbarrel_shifter=1"/>
<definedSymbol symbol="_Interrupt1=_CC(_INTERRUPT1|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Interrupt2=_CC(_INTERRUPT2|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Exception=_CC(_EXCEPTION|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Preserve_flags=_CC(_PRESERVE_FLAGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Save_all_regs=_CC(_SAVE_ALL_REGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Never_returns=_CC(_NEVER_RETURNS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="__arc__=1"/>
<definedSymbol symbol="_ARC_LE=1"/>
<definedSymbol symbol="_LE=1"/>
<definedSymbol symbol="_REENTRANT=1"/>
<definedSymbol symbol="_MT=1"/>
</collector>
</instance>
<instance id="com.arc.cdt.toolchain.arc.exeDebugConfig.1967171072;com.arc.cdt.toolchain.arc.exeDebugConfig.1967171072.1595001667;arc.exe.debug.exeCompilerDebug.606921162;com.arc.cdt.toolchain.arc.inputTypeCPP.1613605697">
<collector id="org.eclipse.cdt.make.core.PerProjectSICollector">
<includePath path="C:\ARC\MetaWare\arc/inc"/>
<includePath path="C:\ARC\MetaWare\arc/incc"/>
<definedSymbol symbol="__HIGHC__"/>
<definedSymbol symbol="_GOC=1"/>
<definedSymbol symbol="_ARC=1"/>
<definedSymbol symbol="_ATT4=1"/>
<definedSymbol symbol="__HAS_LONGLONG=1"/>
<definedSymbol symbol="_ARCOMPACT=1"/>
<definedSymbol symbol="_ARCVER=0x21"/>
<definedSymbol symbol="__Xbarrel_shifter=1"/>
<definedSymbol symbol="_Interrupt1=_CC(_INTERRUPT1|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Interrupt2=_CC(_INTERRUPT2|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Exception=_CC(_EXCEPTION|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Preserve_flags=_CC(_PRESERVE_FLAGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Save_all_regs=_CC(_SAVE_ALL_REGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Never_returns=_CC(_NEVER_RETURNS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="__arc__=1"/>
<definedSymbol symbol="_ARC_LE=1"/>
<definedSymbol symbol="_LE=1"/>
<definedSymbol symbol="_REENTRANT=1"/>
<definedSymbol symbol="_MT=1"/>
</collector>
</instance>
<instance id="com.arc.cdt.toolchain.arc.exeReleaseConfig.1486763645;com.arc.cdt.toolchain.arc.exeReleaseConfig.1486763645.545874047;arc.cdt.toolchain.arc.exeCompilerRelease.53202309;com.arc.cdt.toolchain.arc.inputTypeCPP.1081677297">
<collector id="org.eclipse.cdt.make.core.PerProjectSICollector">
<includePath path="C:\ARC\MetaWare\arc/inc"/>
<includePath path="C:\ARC\MetaWare\arc/incc"/>
<definedSymbol symbol="__HIGHC__"/>
<definedSymbol symbol="_GOC=1"/>
<definedSymbol symbol="_ARC=1"/>
<definedSymbol symbol="_ATT4=1"/>
<definedSymbol symbol="__HAS_LONGLONG=1"/>
<definedSymbol symbol="_ARCOMPACT=1"/>
<definedSymbol symbol="_ARCVER=0x21"/>
<definedSymbol symbol="__Xbarrel_shifter=1"/>
<definedSymbol symbol="_Interrupt1=_CC(_INTERRUPT1|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Interrupt2=_CC(_INTERRUPT2|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Exception=_CC(_EXCEPTION|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Preserve_flags=_CC(_PRESERVE_FLAGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Save_all_regs=_CC(_SAVE_ALL_REGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Never_returns=_CC(_NEVER_RETURNS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="__arc__=1"/>
<definedSymbol symbol="_ARC_LE=1"/>
<definedSymbol symbol="_LE=1"/>
<definedSymbol symbol="_REENTRANT=1"/>
<definedSymbol symbol="_MT=1"/>
</collector>
</instance>
<instance id="com.arc.cdt.toolchain.arc.exeReleaseConfig.1486763645;com.arc.cdt.toolchain.arc.exeReleaseConfig.1486763645.545874047;arc.cdt.toolchain.arc.exeCompilerRelease.53202309;com.arc.cdt.toolchain.arc.inputTypeC.1084715690">
<collector id="org.eclipse.cdt.make.core.PerProjectSICollector">
<includePath path="C:\ARC\MetaWare\arc/inc"/>
<includePath path="C:\ARC\MetaWare\arc/incc"/>
<definedSymbol symbol="__HIGHC__"/>
<definedSymbol symbol="_GOC=1"/>
<definedSymbol symbol="_ARC=1"/>
<definedSymbol symbol="_ATT4=1"/>
<definedSymbol symbol="__HAS_LONGLONG=1"/>
<definedSymbol symbol="_ARCOMPACT=1"/>
<definedSymbol symbol="_ARCVER=0x21"/>
<definedSymbol symbol="__Xbarrel_shifter=1"/>
<definedSymbol symbol="_Interrupt1=_CC(_INTERRUPT1|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Interrupt2=_CC(_INTERRUPT2|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Exception=_CC(_EXCEPTION|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Preserve_flags=_CC(_PRESERVE_FLAGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Save_all_regs=_CC(_SAVE_ALL_REGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Never_returns=_CC(_NEVER_RETURNS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="__arc__=1"/>
<definedSymbol symbol="_ARC_LE=1"/>
<definedSymbol symbol="_LE=1"/>
<definedSymbol symbol="_REENTRANT=1"/>
<definedSymbol symbol="_MT=1"/>
</collector>
</instance>
<instance id="com.arc.cdt.toolchain.arc.exeDebugConfig.1967171072;com.arc.cdt.toolchain.arc.exeDebugConfig.1967171072.588737726;arc.exe.debug.exeCompilerDebug.606921162;com.arc.cdt.toolchain.arc.inputTypeCPP.676662682">
<collector id="org.eclipse.cdt.make.core.PerProjectSICollector">
<includePath path="C:\ARC\MetaWare\arc/inc"/>
<includePath path="C:\ARC\MetaWare\arc/incc"/>
<definedSymbol symbol="__HIGHC__"/>
<definedSymbol symbol="_GOC=1"/>
<definedSymbol symbol="_ARC=1"/>
<definedSymbol symbol="_ATT4=1"/>
<definedSymbol symbol="__HAS_LONGLONG=1"/>
<definedSymbol symbol="_ARCOMPACT=1"/>
<definedSymbol symbol="_ARCVER=0x21"/>
<definedSymbol symbol="__Xbarrel_shifter=1"/>
<definedSymbol symbol="_Interrupt1=_CC(_INTERRUPT1|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Interrupt2=_CC(_INTERRUPT2|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Exception=_CC(_EXCEPTION|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Preserve_flags=_CC(_PRESERVE_FLAGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Save_all_regs=_CC(_SAVE_ALL_REGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Never_returns=_CC(_NEVER_RETURNS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="__arc__=1"/>
<definedSymbol symbol="_ARC_LE=1"/>
<definedSymbol symbol="_LE=1"/>
<definedSymbol symbol="_REENTRANT=1"/>
<definedSymbol symbol="_MT=1"/>
</collector>
</instance>
<instance id="com.arc.cdt.toolchain.arc.exeDebugConfig.1967171072;com.arc.cdt.toolchain.arc.exeDebugConfig.1967171072.588737726;arc.exe.debug.exeCompilerDebug.606921162;com.arc.cdt.toolchain.arc.inputTypeC.737203268">
<collector id="org.eclipse.cdt.make.core.PerProjectSICollector">
<includePath path="C:\ARC\MetaWare\arc/inc"/>
<includePath path="C:\ARC\MetaWare\arc/incc"/>
<definedSymbol symbol="__HIGHC__"/>
<definedSymbol symbol="_GOC=1"/>
<definedSymbol symbol="_ARC=1"/>
<definedSymbol symbol="_ATT4=1"/>
<definedSymbol symbol="__HAS_LONGLONG=1"/>
<definedSymbol symbol="_ARCOMPACT=1"/>
<definedSymbol symbol="_ARCVER=0x21"/>
<definedSymbol symbol="__Xbarrel_shifter=1"/>
<definedSymbol symbol="_Interrupt1=_CC(_INTERRUPT1|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Interrupt2=_CC(_INTERRUPT2|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Exception=_CC(_EXCEPTION|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Preserve_flags=_CC(_PRESERVE_FLAGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Save_all_regs=_CC(_SAVE_ALL_REGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Never_returns=_CC(_NEVER_RETURNS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="__arc__=1"/>
<definedSymbol symbol="_ARC_LE=1"/>
<definedSymbol symbol="_LE=1"/>
<definedSymbol symbol="_REENTRANT=1"/>
<definedSymbol symbol="_MT=1"/>
</collector>
</instance>
<instance id="com.arc.cdt.toolchain.arc.exeReleaseConfig.1486763645;com.arc.cdt.toolchain.arc.exeReleaseConfig.1486763645.1854330236;arc.cdt.toolchain.arc.exeCompilerRelease.53202309;com.arc.cdt.toolchain.arc.inputTypeCPP.1813601266">
<collector id="org.eclipse.cdt.make.core.PerProjectSICollector">
<includePath path="C:\ARC\MetaWare\arc/inc"/>
<includePath path="C:\ARC\MetaWare\arc/incc"/>
<definedSymbol symbol="__HIGHC__"/>
<definedSymbol symbol="_GOC=1"/>
<definedSymbol symbol="_ARC=1"/>
<definedSymbol symbol="_ATT4=1"/>
<definedSymbol symbol="__HAS_LONGLONG=1"/>
<definedSymbol symbol="_ARCOMPACT=1"/>
<definedSymbol symbol="_ARCVER=0x21"/>
<definedSymbol symbol="__Xbarrel_shifter=1"/>
<definedSymbol symbol="_Interrupt1=_CC(_INTERRUPT1|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Interrupt2=_CC(_INTERRUPT2|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Exception=_CC(_EXCEPTION|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Preserve_flags=_CC(_PRESERVE_FLAGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Save_all_regs=_CC(_SAVE_ALL_REGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Never_returns=_CC(_NEVER_RETURNS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="__arc__=1"/>
<definedSymbol symbol="_ARC_LE=1"/>
<definedSymbol symbol="_LE=1"/>
<definedSymbol symbol="_REENTRANT=1"/>
<definedSymbol symbol="_MT=1"/>
</collector>
</instance>
<instance id="com.arc.cdt.toolchain.arc.exeReleaseConfig.1486763645;com.arc.cdt.toolchain.arc.exeReleaseConfig.1486763645.1854330236;arc.cdt.toolchain.arc.exeCompilerRelease.53202309;com.arc.cdt.toolchain.arc.inputTypeC.1681926877">
<collector id="org.eclipse.cdt.make.core.PerProjectSICollector">
<includePath path="C:\ARC\MetaWare\arc/inc"/>
<includePath path="C:\ARC\MetaWare\arc/incc"/>
<definedSymbol symbol="__HIGHC__"/>
<definedSymbol symbol="_GOC=1"/>
<definedSymbol symbol="_ARC=1"/>
<definedSymbol symbol="_ATT4=1"/>
<definedSymbol symbol="__HAS_LONGLONG=1"/>
<definedSymbol symbol="_ARCOMPACT=1"/>
<definedSymbol symbol="_ARCVER=0x21"/>
<definedSymbol symbol="__Xbarrel_shifter=1"/>
<definedSymbol symbol="_Interrupt1=_CC(_INTERRUPT1|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Interrupt2=_CC(_INTERRUPT2|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Exception=_CC(_EXCEPTION|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Preserve_flags=_CC(_PRESERVE_FLAGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Save_all_regs=_CC(_SAVE_ALL_REGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Never_returns=_CC(_NEVER_RETURNS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="__arc__=1"/>
<definedSymbol symbol="_ARC_LE=1"/>
<definedSymbol symbol="_LE=1"/>
<definedSymbol symbol="_REENTRANT=1"/>
<definedSymbol symbol="_MT=1"/>
</collector>
</instance>
<instance id="com.arc.cdt.toolchain.arc.exeDebugConfig.1967171072;com.arc.cdt.toolchain.arc.exeDebugConfig.1967171072.588737726;arc.exe.debug.exeCompilerDebug.606921162;com.arc.cdt.toolchain.arc.inputTypeC.989989751">
<collector id="org.eclipse.cdt.make.core.PerProjectSICollector">
<includePath path="C:\ARC\MetaWare\arc/inc"/>
<includePath path="C:\ARC\MetaWare\arc/incc"/>
<definedSymbol symbol="__HIGHC__"/>
<definedSymbol symbol="_GOC=1"/>
<definedSymbol symbol="_ARC=1"/>
<definedSymbol symbol="_ATT4=1"/>
<definedSymbol symbol="__HAS_LONGLONG=1"/>
<definedSymbol symbol="_ARCOMPACT=1"/>
<definedSymbol symbol="_ARCVER=0x21"/>
<definedSymbol symbol="__Xbarrel_shifter=1"/>
<definedSymbol symbol="_Interrupt1=_CC(_INTERRUPT1|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Interrupt2=_CC(_INTERRUPT2|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Exception=_CC(_EXCEPTION|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Preserve_flags=_CC(_PRESERVE_FLAGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Save_all_regs=_CC(_SAVE_ALL_REGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Never_returns=_CC(_NEVER_RETURNS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="__arc__=1"/>
<definedSymbol symbol="_ARC_LE=1"/>
<definedSymbol symbol="_LE=1"/>
<definedSymbol symbol="_REENTRANT=1"/>
<definedSymbol symbol="_MT=1"/>
</collector>
</instance>
<instance id="com.arc.cdt.toolchain.arc.exeDebugConfig.1967171072;com.arc.cdt.toolchain.arc.exeDebugConfig.1967171072.588737726;arc.exe.debug.exeCompilerDebug.606921162;com.arc.cdt.toolchain.arc.inputTypeCPP.1193410422">
<collector id="org.eclipse.cdt.make.core.PerProjectSICollector">
<includePath path="C:\ARC\MetaWare\arc/inc"/>
<includePath path="C:\ARC\MetaWare\arc/incc"/>
<definedSymbol symbol="__HIGHC__"/>
<definedSymbol symbol="_GOC=1"/>
<definedSymbol symbol="_ARC=1"/>
<definedSymbol symbol="_ATT4=1"/>
<definedSymbol symbol="__HAS_LONGLONG=1"/>
<definedSymbol symbol="_ARCOMPACT=1"/>
<definedSymbol symbol="_ARCVER=0x21"/>
<definedSymbol symbol="__Xbarrel_shifter=1"/>
<definedSymbol symbol="_Interrupt1=_CC(_INTERRUPT1|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Interrupt2=_CC(_INTERRUPT2|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Exception=_CC(_EXCEPTION|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Preserve_flags=_CC(_PRESERVE_FLAGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Save_all_regs=_CC(_SAVE_ALL_REGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Never_returns=_CC(_NEVER_RETURNS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="__arc__=1"/>
<definedSymbol symbol="_ARC_LE=1"/>
<definedSymbol symbol="_LE=1"/>
<definedSymbol symbol="_REENTRANT=1"/>
<definedSymbol symbol="_MT=1"/>
</collector>
</instance>
<instance id="com.arc.cdt.toolchain.arc.exeReleaseConfig.1486763645;com.arc.cdt.toolchain.arc.exeReleaseConfig.1486763645.1854330236;arc.cdt.toolchain.arc.exeCompilerRelease.53202309;com.arc.cdt.toolchain.arc.inputTypeC.738837997">
<collector id="org.eclipse.cdt.make.core.PerProjectSICollector">
<includePath path="C:\ARC\MetaWare\arc/inc"/>
<includePath path="C:\ARC\MetaWare\arc/incc"/>
<definedSymbol symbol="__HIGHC__"/>
<definedSymbol symbol="_GOC=1"/>
<definedSymbol symbol="_ARC=1"/>
<definedSymbol symbol="_ATT4=1"/>
<definedSymbol symbol="__HAS_LONGLONG=1"/>
<definedSymbol symbol="_ARCOMPACT=1"/>
<definedSymbol symbol="_ARCVER=0x21"/>
<definedSymbol symbol="__Xbarrel_shifter=1"/>
<definedSymbol symbol="_Interrupt1=_CC(_INTERRUPT1|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Interrupt2=_CC(_INTERRUPT2|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Exception=_CC(_EXCEPTION|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Preserve_flags=_CC(_PRESERVE_FLAGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Save_all_regs=_CC(_SAVE_ALL_REGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Never_returns=_CC(_NEVER_RETURNS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="__arc__=1"/>
<definedSymbol symbol="_ARC_LE=1"/>
<definedSymbol symbol="_LE=1"/>
<definedSymbol symbol="_REENTRANT=1"/>
<definedSymbol symbol="_MT=1"/>
</collector>
</instance>
<instance id="com.arc.cdt.toolchain.arc.exeReleaseConfig.1486763645;com.arc.cdt.toolchain.arc.exeReleaseConfig.1486763645.1854330236;arc.cdt.toolchain.arc.exeCompilerRelease.53202309;com.arc.cdt.toolchain.arc.inputTypeCPP.426136475">
<collector id="org.eclipse.cdt.make.core.PerProjectSICollector">
<includePath path="C:\ARC\MetaWare\arc/inc"/>
<includePath path="C:\ARC\MetaWare\arc/incc"/>
<definedSymbol symbol="__HIGHC__"/>
<definedSymbol symbol="_GOC=1"/>
<definedSymbol symbol="_ARC=1"/>
<definedSymbol symbol="_ATT4=1"/>
<definedSymbol symbol="__HAS_LONGLONG=1"/>
<definedSymbol symbol="_ARCOMPACT=1"/>
<definedSymbol symbol="_ARCVER=0x21"/>
<definedSymbol symbol="__Xbarrel_shifter=1"/>
<definedSymbol symbol="_Interrupt1=_CC(_INTERRUPT1|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Interrupt2=_CC(_INTERRUPT2|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Exception=_CC(_EXCEPTION|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Preserve_flags=_CC(_PRESERVE_FLAGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Save_all_regs=_CC(_SAVE_ALL_REGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Never_returns=_CC(_NEVER_RETURNS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="__arc__=1"/>
<definedSymbol symbol="_ARC_LE=1"/>
<definedSymbol symbol="_LE=1"/>
<definedSymbol symbol="_REENTRANT=1"/>
<definedSymbol symbol="_MT=1"/>
</collector>
</instance>
<instance id="com.arc.cdt.toolchain.arc.exeDebugConfig.1967171072;com.arc.cdt.toolchain.arc.exeDebugConfig.1967171072.588737726;arc.exe.debug.exeCompilerDebug.606921162;com.arc.cdt.toolchain.arc.inputTypeC.974749165">
<collector id="org.eclipse.cdt.make.core.PerProjectSICollector">
<includePath path="C:\ARC\MetaWare\arc/inc"/>
<includePath path="C:\ARC\MetaWare\arc/incc"/>
<definedSymbol symbol="__HIGHC__"/>
<definedSymbol symbol="_GOC=1"/>
<definedSymbol symbol="_ARC=1"/>
<definedSymbol symbol="_ATT4=1"/>
<definedSymbol symbol="__HAS_LONGLONG=1"/>
<definedSymbol symbol="_ARCOMPACT=1"/>
<definedSymbol symbol="_ARCVER=0x21"/>
<definedSymbol symbol="__Xbarrel_shifter=1"/>
<definedSymbol symbol="_Interrupt1=_CC(_INTERRUPT1|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Interrupt2=_CC(_INTERRUPT2|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Exception=_CC(_EXCEPTION|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Preserve_flags=_CC(_PRESERVE_FLAGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Save_all_regs=_CC(_SAVE_ALL_REGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Never_returns=_CC(_NEVER_RETURNS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="__arc__=1"/>
<definedSymbol symbol="_ARC_LE=1"/>
<definedSymbol symbol="_LE=1"/>
<definedSymbol symbol="_REENTRANT=1"/>
<definedSymbol symbol="_MT=1"/>
</collector>
</instance>
<instance id="com.arc.cdt.toolchain.arc.exeDebugConfig.1967171072;com.arc.cdt.toolchain.arc.exeDebugConfig.1967171072.588737726;arc.exe.debug.exeCompilerDebug.606921162;com.arc.cdt.toolchain.arc.inputTypeCPP.1457457632">
<collector id="org.eclipse.cdt.make.core.PerProjectSICollector">
<includePath path="C:\ARC\MetaWare\arc/inc"/>
<includePath path="C:\ARC\MetaWare\arc/incc"/>
<definedSymbol symbol="__HIGHC__"/>
<definedSymbol symbol="_GOC=1"/>
<definedSymbol symbol="_ARC=1"/>
<definedSymbol symbol="_ATT4=1"/>
<definedSymbol symbol="__HAS_LONGLONG=1"/>
<definedSymbol symbol="_ARCOMPACT=1"/>
<definedSymbol symbol="_ARCVER=0x21"/>
<definedSymbol symbol="__Xbarrel_shifter=1"/>
<definedSymbol symbol="_Interrupt1=_CC(_INTERRUPT1|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Interrupt2=_CC(_INTERRUPT2|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Exception=_CC(_EXCEPTION|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Preserve_flags=_CC(_PRESERVE_FLAGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Save_all_regs=_CC(_SAVE_ALL_REGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Never_returns=_CC(_NEVER_RETURNS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="__arc__=1"/>
<definedSymbol symbol="_ARC_LE=1"/>
<definedSymbol symbol="_LE=1"/>
<definedSymbol symbol="_REENTRANT=1"/>
<definedSymbol symbol="_MT=1"/>
</collector>
</instance>
<instance id="com.arc.cdt.toolchain.arc.exeReleaseConfig.1486763645;com.arc.cdt.toolchain.arc.exeReleaseConfig.1486763645.1854330236;arc.cdt.toolchain.arc.exeCompilerRelease.53202309;com.arc.cdt.toolchain.arc.inputTypeCPP.1830486664">
<collector id="org.eclipse.cdt.make.core.PerProjectSICollector">
<includePath path="C:\ARC\MetaWare\arc/inc"/>
<includePath path="C:\ARC\MetaWare\arc/incc"/>
<definedSymbol symbol="__HIGHC__"/>
<definedSymbol symbol="_GOC=1"/>
<definedSymbol symbol="_ARC=1"/>
<definedSymbol symbol="_ATT4=1"/>
<definedSymbol symbol="__HAS_LONGLONG=1"/>
<definedSymbol symbol="_ARCOMPACT=1"/>
<definedSymbol symbol="_ARCVER=0x21"/>
<definedSymbol symbol="__Xbarrel_shifter=1"/>
<definedSymbol symbol="_Interrupt1=_CC(_INTERRUPT1|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Interrupt2=_CC(_INTERRUPT2|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Exception=_CC(_EXCEPTION|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Preserve_flags=_CC(_PRESERVE_FLAGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Save_all_regs=_CC(_SAVE_ALL_REGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Never_returns=_CC(_NEVER_RETURNS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="__arc__=1"/>
<definedSymbol symbol="_ARC_LE=1"/>
<definedSymbol symbol="_LE=1"/>
<definedSymbol symbol="_REENTRANT=1"/>
<definedSymbol symbol="_MT=1"/>
</collector>
</instance>
<instance id="com.arc.cdt.toolchain.arc.exeReleaseConfig.1486763645;com.arc.cdt.toolchain.arc.exeReleaseConfig.1486763645.1854330236;arc.cdt.toolchain.arc.exeCompilerRelease.53202309;com.arc.cdt.toolchain.arc.inputTypeC.2040010676">
<collector id="org.eclipse.cdt.make.core.PerProjectSICollector">
<includePath path="C:\ARC\MetaWare\arc/inc"/>
<includePath path="C:\ARC\MetaWare\arc/incc"/>
<definedSymbol symbol="__HIGHC__"/>
<definedSymbol symbol="_GOC=1"/>
<definedSymbol symbol="_ARC=1"/>
<definedSymbol symbol="_ATT4=1"/>
<definedSymbol symbol="__HAS_LONGLONG=1"/>
<definedSymbol symbol="_ARCOMPACT=1"/>
<definedSymbol symbol="_ARCVER=0x21"/>
<definedSymbol symbol="__Xbarrel_shifter=1"/>
<definedSymbol symbol="_Interrupt1=_CC(_INTERRUPT1|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Interrupt2=_CC(_INTERRUPT2|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Exception=_CC(_EXCEPTION|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Preserve_flags=_CC(_PRESERVE_FLAGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Save_all_regs=_CC(_SAVE_ALL_REGS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="_Never_returns=_CC(_NEVER_RETURNS|_DEFAULT_CALLING_CONVENTION)"/>
<definedSymbol symbol="__arc__=1"/>
<definedSymbol symbol="_ARC_LE=1"/>
<definedSymbol symbol="_LE=1"/>
<definedSymbol symbol="_REENTRANT=1"/>
<definedSymbol symbol="_MT=1"/>
</collector>
</instance>
</scannerInfo>
