
/* Generated by mcsg V1.0.0
 * 
 */
#ifndef VR_APPLICATION_INCLUDE_H
#define VR_APPLICATION_INCLUDE_H

#include "vr_include_all.h"
#include "vr_application_defines.h"
#include "vr_application_main.h"

#define vr_get_malloc_byte_alignment_gap_board_os_based(size) \
           ((8- ((size) % 8)) % 8)


#endif /* VR_APPLICATION_INCLUDE_H */
