/**********************************************************************
*    This file was generated by Design Tool a product of: 
*       ARC International  
*       http://www.ARC.com/         
*                              
*       Mon Mar 12 09:32:23 2007
*   
*       Copyright (c) ARC International  
*       All rights reserved    
*   
*       This software embodies materials and concepts which are
*       confidential to ARC International and is made
*       available solely pursuant to the terms of a written license
*       agreement with ARC International.
*   
*   ********************************************************************/
/* 
*  Resources  -   Number -  Memory Required
*  Kernel       -   N/A       -  0x274c
*  Tasks        - 11       -  0x2530
*  Msg Pools    -  1 of 2  -   0x1a4
*  Msg Queues   -  3 of 12   -  0x1a0
*  Mutexes       -  1    -  0x24
*  Semaphores   -  1 of 10  -  0x280
*  Events       -  1 of 10   -    0x2a0
*  Logs         -  1 of 16    -  0x1344
*  	   Total:  0x6848 or 26696
*/ 
#include <mqx.h>
#include <bsp.h>
#include <message.h>
#include <errno.h>
#include <mutex.h>
#include <sem.h>
#include <event.h>
#include <log.h>
#include <klog.h>
#include "demo.h"

/*   Task Code -  EventA     */

/*TASK---------------------------------------------------------------
*
* Task Name   :  EventA
* Comments    :  
*
*END*--------------------------------------------------------------*/

void EventA
   (
      uint_32  parameter
   )
{
   _mqx_uint         event_result;
   pointer   Event1_handle;

   /* create event - event.Event1 */
   event_result = _event_create("event.Event1");
   if (event_result != MQX_OK) {
      /* event could not be created */
   } /*Endif*/
   /* open connection to event event.Event1 */
   event_result = _event_open("event.Event1", &Event1_handle);
   if (event_result != MQX_OK) {
      /* could not open event */
   } /*Endif*/
   /*
   ** LOOP - 
   */
   while (TRUE) {
      /* set event event.Event1 */
      event_result = _event_set(Event1_handle, (_mqx_uint)0x1);
      if (event_result != MQX_OK) {
         /* setting the event failed */
      } /*Endif*/
      _time_delay_ticks((_mqx_uint)1);
   } /* Endwhile */ 
} /*EndBody*/

/* End of File */
