/**********************************************************************
*    This file was generated by Design Tool a product of: 
*       ARC International  
*       http://www.ARC.com/         
*                              
*       Mon Mar 12 09:32:23 2007
*   
*       Copyright (c) ARC International  
*       All rights reserved    
*   
*       This software embodies materials and concepts which are
*       confidential to ARC International and is made
*       available solely pursuant to the terms of a written license
*       agreement with ARC International.
*   
*   ********************************************************************/
/* 
*  Resources  -   Number -  Memory Required
*  Kernel       -   N/A       -  0x274c
*  Tasks        - 11       -  0x2530
*  Msg Pools    -  1 of 2  -   0x1a4
*  Msg Queues   -  3 of 12   -  0x1a0
*  Mutexes       -  1    -  0x24
*  Semaphores   -  1 of 10  -  0x280
*  Events       -  1 of 10   -    0x2a0
*  Logs         -  1 of 16    -  0x1344
*  	   Total:  0x6848 or 26696
*/ 
#include <mqx.h>
#include <bsp.h>
#include <message.h>
#include <errno.h>
#include <mutex.h>
#include <sem.h>
#include <event.h>
#include <log.h>
#include <klog.h>
#include "demo.h"

/*   Task Code -  Main     */

/*TASK---------------------------------------------------------------
*
* Task Name   :  Main
* Comments    :  
*
*END*--------------------------------------------------------------*/

void Main
   (
      uint_32  parameter
   )
{
   _mqx_uint         log_result;
   _task_id    created_task;
   MESSAGE_HEADER_STRUCT_PTR   msg_ptr;
   _mqx_uint         event_result;
   _mqx_uint         sem_result;

   printf("\n\nMQX 2.52\n");
   printf("Hello from Main()");
   /* Create the mutex component */
   if (_mutex_create_component() != MQX_OK) {
      /* an error has been detected */
   } /*Endif*/
   /* create the event component */
   event_result = _event_create_component((_mqx_uint)EVENT_INITIAL_NUMBER,
      (_mqx_uint)EVENT_GROWTH, (_mqx_uint)EVENT_MAXIMUM);
   if (event_result != MQX_OK) {
      /* event component could not be created */
   } /*Endif*/
   /* create the semaphore component */
   sem_result = _sem_create_component((_mqx_uint)SEM_INITIAL_NUMBER,
      (_mqx_uint)SEM_GROWTH, (_mqx_uint)SEM_MAXIMUM);
   if (sem_result != MQX_OK) {
      /* semaphore component could not be created */
   } /*Endif*/
   /* 
   ** NOTE: Ensure that the size parameter is set to the size
    ** of the largest message that will be allocated from this pool.
   */
   MsgPool_pool_id = _msgpool_create(8, 10, 0, 0);
   if (MsgPool_pool_id == MSGPOOL_NULL_POOL_ID) {
      /* _msgpool_create did not succeed */
   } /*Endif*/
   Main_Queue_qid = _msgq_open(MSGQ_FREE_QUEUE, SIZE_UNLIMITED);
   if (Main_Queue_qid == MSGQ_NULL_QUEUE_ID) {
      /* queue could not be opened */
   } /*Endif*/
   created_task = _task_create(0, SENDER_INDEX, 0);
   if (created_task == MQX_NULL_TASK_ID) {
      /* task creation failed */
   } /*Endif*/
   created_task = _task_create(0, MUTEXA_INDEX, 0);
   if (created_task == MQX_NULL_TASK_ID) {
      /* task creation failed */
   } /*Endif*/
   created_task = _task_create(0, MUTEXB_INDEX, 0);
   if (created_task == MQX_NULL_TASK_ID) {
      /* task creation failed */
   } /*Endif*/
   created_task = _task_create(0, SEMA_INDEX, 0);
   if (created_task == MQX_NULL_TASK_ID) {
      /* task creation failed */
   } /*Endif*/
   created_task = _task_create(0, SEMB_INDEX, 0);
   if (created_task == MQX_NULL_TASK_ID) {
      /* task creation failed */
   } /*Endif*/
   created_task = _task_create(0, EVENTA_INDEX, 0);
   if (created_task == MQX_NULL_TASK_ID) {
      /* task creation failed */
   } /*Endif*/
   created_task = _task_create(0, EVENTB_INDEX, 0);
   if (created_task == MQX_NULL_TASK_ID) {
      /* task creation failed */
   } /*Endif*/
   /* create kernel log  */
   log_result = _klog_create((_mqx_uint)1200, (_mqx_uint)0);
   if (log_result != MQX_OK) {
      /* log could not be created */
   } /*Endif*/
   /* define kernel logging */
   _klog_control((uint_32)0xffffffff, FALSE);
   _klog_control(KLOG_ENABLED |
                 KLOG_FUNCTIONS_ENABLED |
                 KLOG_INTERRUPTS_ENABLED |
                 KLOG_SYSTEM_CLOCK_INT_ENABLED |
                 KLOG_CONTEXT_ENABLED |
                 KLOG_TASKING_FUNCTIONS |
                 KLOG_ERROR_FUNCTIONS |
                 KLOG_MESSAGE_FUNCTIONS |
                 KLOG_INTERRUPT_FUNCTIONS |
                 KLOG_MEMORY_FUNCTIONS |
                 KLOG_TIME_FUNCTIONS |
                 KLOG_EVENT_FUNCTIONS |
                 KLOG_NAME_FUNCTIONS |
                 KLOG_MUTEX_FUNCTIONS |
                 KLOG_SEMAPHORE_FUNCTIONS |
                 KLOG_WATCHDOG_FUNCTIONS, TRUE);
   /*
   ** LOOP - 
   */
   while (TRUE) {
      msg_ptr = _msg_alloc((_pool_id)MsgPool_pool_id);
      if (msg_ptr == NULL) {
         /* No available message buffer */
      } /*Endif*/
      msg_ptr->SOURCE_QID = msg_ptr->TARGET_QID;
      msg_ptr->TARGET_QID = Sender_Queue_qid;
      _msgq_send(msg_ptr);

      /*
      ** Service the message queue - Main_Queue
      */
      msg_ptr = _msgq_receive(Main_Queue_qid, (_mqx_uint)NO_TIMEOUT);
      /* process message End_msg */
      _msg_free(msg_ptr);

   } /* Endwhile */ 
} /*EndBody*/

/* End of File */
