/**********************************************************************
*    This file was generated by Design Tool a product of: 
*       ARC International  
*       http://www.ARC.com/         
*                              
*       Mon Mar 12 09:32:22 2007
*   
*       Copyright (c) ARC International  
*       All rights reserved    
*   
*       This software embodies materials and concepts which are
*       confidential to ARC International and is made
*       available solely pursuant to the terms of a written license
*       agreement with ARC International.
*   
*   ********************************************************************/
/* 
*  Resources  -   Number -  Memory Required
*  Kernel       -   N/A       -  0x274c
*  Tasks        - 11       -  0x2530
*  Msg Pools    -  1 of 2  -   0x1a4
*  Msg Queues   -  3 of 12   -  0x1a0
*  Mutexes       -  1    -  0x24
*  Semaphores   -  1 of 10  -  0x280
*  Events       -  1 of 10   -    0x2a0
*  Logs         -  1 of 16    -  0x1344
*  	   Total:  0x6848 or 26696
*/ 
#include <mqx.h>
#include <bsp.h>
#include <message.h>
#include <errno.h>
#include <mutex.h>
#include <sem.h>
#include <event.h>
#include <log.h>
#include <klog.h>
#include "demo.h"

/*   Task Code -  MutexB     */

/*TASK---------------------------------------------------------------
*
* Task Name   :  MutexB
* Comments    :  
*
*END*--------------------------------------------------------------*/

void MutexB
   (
      uint_32  parameter
   )
{

   /*
   ** LOOP - 
   */
   while (TRUE) {
      if (_mutex_lock(&Mutex1) != MQX_EOK) {
         /* an error occurred */
      } /*Endif*/
      /* access shared resource */

      _time_delay_ticks((_mqx_uint)1);
      _mutex_unlock(&Mutex1);
   } /* Endwhile */ 
} /*EndBody*/

/* End of File */
