/**********************************************************************
*    This file was generated by Design Tool a product of: 
*       ARC International  
*       http://www.ARC.com/         
*                              
*       Mon Mar 12 09:32:22 2007
*   
*       Copyright (c) ARC International  
*       All rights reserved    
*   
*       This software embodies materials and concepts which are
*       confidential to ARC International and is made
*       available solely pursuant to the terms of a written license
*       agreement with ARC International.
*   
*   ********************************************************************/
/*   Task Templates and 
**   MQX Initialization Structure, if required 
*/
/* 
*  Resources  -   Number -  Memory Required
*  Kernel       -   N/A       -  0x274c
*  Tasks        - 11       -  0x2530
*  Msg Pools    -  1 of 2  -   0x1a4
*  Msg Queues   -  3 of 12   -  0x1a0
*  Mutexes       -  1    -  0x24
*  Semaphores   -  1 of 10  -  0x280
*  Events       -  1 of 10   -    0x2a0
*  Logs         -  1 of 16    -  0x1344
*  	   Total:  0x6848 or 26696
*/ 
#include <mqx.h>
#include <bsp.h>
#include <message.h>
#include <errno.h>
#include <mutex.h>
#include <sem.h>
#include <event.h>
#include <log.h>
#include <klog.h>
#include "demo.h"

/*   Task Templates  */ 
TASK_TEMPLATE_STRUCT  MQX_template_list[] = {
   { MUTEXB_INDEX, MutexB, 0x320L, 9L, "MutexB",
       0L, 0L, 0L },
   { MUTEXA_INDEX, MutexA, 0x320L, 9L, "MutexA",
       0L, 0L, 0L },
   { SEMB_INDEX, SemB, 0x320L, 10L, "SemB",
       0L, 0L, 0L },
   { SEMA_INDEX, SemA, 0x320L, 9L, "SemA",
       0L, 0L, 0L },
   { EVENTB_INDEX, EventB, 0x320L, 9L, "EventB",
       0L, 0L, 0L },
   { EVENTA_INDEX, EventA, 0x320L, 9L, "EventA",
       0L, 0L, 0L },
   { BTIMESLICETASK_INDEX, BTimeSliceTask, 0x320L, 9L, "BTimeSliceTask",
       MQX_AUTO_START_TASK, 0, 0L },
   { ATIMESLICETASK_INDEX, ATimeSliceTask, 0x320L, 9L, "ATimeSliceTask",
       MQX_TIME_SLICE_TASK | MQX_AUTO_START_TASK, 0, 0L },
   { SENDER_INDEX, Sender, 0x320L, 10L, "Sender",
       0L, 0L, 0L },
   { RESPONDER_INDEX, Responder, 0x41aL, 9L, "Responder",
       0L, 0L, 0L },
   { MAIN_INDEX, Main, 0x41aL, 11L, "Main",
       MQX_AUTO_START_TASK, 0, 0L },
   { 0, 0, 0, 0, 0, 0, 0, 0}
};



/*   MQX Initialization  */ 
MQX_INITIALIZATION_STRUCT  MQX_init_struct = {
   /* PROCESSOR_NUMBER                */  BSP_DEFAULT_PROCESSOR_NUMBER,
   /* START_OF_KERNEL_MEMORY          */  BSP_DEFAULT_START_OF_KERNEL_MEMORY,
   /* END_OF_KERNEL_MEMORY            */  BSP_DEFAULT_END_OF_KERNEL_MEMORY,
   /* INTERRUPT_STACK_SIZE            */  BSP_DEFAULT_INTERRUPT_STACK_SIZE,
   /* TASK_TEMPLATE_LIST              */  (pointer)MQX_template_list,
   /* MQX_HARDWARE_INTERRUPT_LEVEL_MAX*/  BSP_DEFAULT_MQX_HARDWARE_INTERRUPT_LEVEL_MAX,
   /* MAX_BUFFER_POOLS                */  2, 
   /* MAX_QUEUE_NUMBER                */  12, 
   /* IO_CHANNEL                      */  BSP_DEFAULT_IO_CHANNEL,
   /* IO_OPEN_MODE                    */  BSP_DEFAULT_IO_OPEN_MODE
};


/* End of File */
