/**********************************************************************
*    This file was generated by Design Tool a product of: 
*       ARC International  
*       http://www.ARC.com/         
*                              
*       Mon Mar 12 09:32:23 2007
*   
*       Copyright (c) ARC International  
*       All rights reserved    
*   
*       This software embodies materials and concepts which are
*       confidential to ARC International and is made
*       available solely pursuant to the terms of a written license
*       agreement with ARC International.
*   
*   ********************************************************************/
/* 
*  Resources  -   Number -  Memory Required
*  Kernel       -   N/A       -  0x274c
*  Tasks        - 11       -  0x2530
*  Msg Pools    -  1 of 2  -   0x1a4
*  Msg Queues   -  3 of 12   -  0x1a0
*  Mutexes       -  1    -  0x24
*  Semaphores   -  1 of 10  -  0x280
*  Events       -  1 of 10   -    0x2a0
*  Logs         -  1 of 16    -  0x1344
*  	   Total:  0x6848 or 26696
*/ 
#include <mqx.h>
#include <bsp.h>
#include <message.h>
#include <errno.h>
#include <mutex.h>
#include <sem.h>
#include <event.h>
#include <log.h>
#include <klog.h>
#include "demo.h"

#if MQX_USE_PMU
#include <pmu.h>
#endif

/*   Task Code -  Main     */

/*TASK---------------------------------------------------------------
*
* Task Name   :  Main
* Comments    :  
*
*END*--------------------------------------------------------------*/



void Main
   (
      uint_32  parameter
   )
{
   _mqx_uint         log_result;
   _task_id          created_task;
   MESSAGE_HEADER_STRUCT_PTR   msg_ptr;
   _mqx_uint         event_result;
   _mqx_uint         sem_result;
   _mqx_uint         result;


    printf("\n\nMQX-EP 2.52\n");

#if DEMO_AUTO_DVFS
	printf("Using Automatic DVFS Mode\n");
#endif

#if DEMO_GLOBAL_DVFS_MODE
   	printf("Global DVFS Mode=%d\n", DEMO_GLOBAL_DVFS_MODE);
#endif 

#if GDVFS_DELAY
    printf("Global/Auto DVFS Load Setting=%d\n",GDVFS_DELAY );
#endif

#if DEMO_POWER_DOWN
   	printf("Power Down Enabled, Threshold is=%d\n", DEMO_POWER_DOWN);
#endif 

#if DEMO_SLOW_DOWN
   	printf("Clock Slow Down Enabled, Threshold is=%d\n", DEMO_SLOW_DOWN);
#endif 

#if SENDER_DVFS_MODE
	printf("Sender DVFS Mode=%d\n",SENDER_DVFS_MODE );
#if SENDER_DELAY
    printf("Sender Load Setting=%d\n",SENDER_DELAY );
#endif
#endif

#if RESPONDER_DVFS_MODE
	printf("Responder DVFS Mode=%d\n",RESPONDER_DVFS_MODE );
#if RESPONDER_DELAY
	printf("Responder Load Setting=%d\n",RESPONDER_DELAY );
#endif
#endif

#if EVENTA_DVFS_MODE
	printf("EventA DVFS Mode=%d\n",EVENTA_DVFS_MODE );
#if EVENTA_DELAY
    printf("EventA Load Setting=%d\n",EVENTA_DELAY );
#endif
#endif

#if EVENTB_DVFS_MODE
	printf("EventB DVFS Mode=%d\n",EVENTB_DVFS_MODE );
#if EVENTB_DELAY
    printf("EventB Load Setting=%d\n",EVENTB_DELAY );
#endif
#endif



   /* Create the mutex component */
   if (_mutex_create_component() != MQX_OK) {
      /* an error has been detected */
   } /*Endif*/
   /* create the event component */
   event_result = _event_create_component((_mqx_uint)EVENT_INITIAL_NUMBER,
      (_mqx_uint)EVENT_GROWTH, (_mqx_uint)EVENT_MAXIMUM);
   if (event_result != MQX_OK) {
      /* event component could not be created */
   } /*Endif*/
   /* create the semaphore component */
   sem_result = _sem_create_component((_mqx_uint)SEM_INITIAL_NUMBER,
      (_mqx_uint)SEM_GROWTH, (_mqx_uint)SEM_MAXIMUM);
   if (sem_result != MQX_OK) {
      /* semaphore component could not be created */
   } /*Endif*/
   /* 
   ** NOTE: Ensure that the size parameter is set to the size
    ** of the largest message that will be allocated from this pool.
   */
   MsgPool_pool_id = _msgpool_create(8, 10, 0, 0);
   if (MsgPool_pool_id == MSGPOOL_NULL_POOL_ID) {
      /* _msgpool_create did not succeed */
   } /*Endif*/
   Main_Queue_qid = _msgq_open(MSGQ_FREE_QUEUE, SIZE_UNLIMITED);
   if (Main_Queue_qid == MSGQ_NULL_QUEUE_ID) {
      /* queue could not be opened */
   } /*Endif*/


   created_task = _task_create(0, SENDER_INDEX, 0);
   if (created_task == MQX_NULL_TASK_ID) {
      /* task creation failed */
   } /*Endif*/

#if SENDER_DVFS_MODE
	result = _ep_dvfs_set_mode(created_task, SENDER_DVFS_MODE);
	if (result != MQX_OK) {
		/* Error setting DVFS mode for task */
		printf("\nError setting DVFS mode for task %d.\n", created_task);
	} /* Endif */
#endif

   created_task = _task_create(0, MUTEXA_INDEX, 0);
   if (created_task == MQX_NULL_TASK_ID) {
      /* task creation failed */
   } /*Endif*/

   created_task = _task_create(0, MUTEXB_INDEX, 0);
   if (created_task == MQX_NULL_TASK_ID) {
      /* task creation failed */
   } /*Endif*/

   created_task = _task_create(0, SEMA_INDEX, 0);
   if (created_task == MQX_NULL_TASK_ID) {
      /* task creation failed */
   } /*Endif*/

   created_task = _task_create(0, SEMB_INDEX, 0);
   if (created_task == MQX_NULL_TASK_ID) {
      /* task creation failed */
   } /*Endif*/


   created_task = _task_create(0, EVENTA_INDEX, 0);
   if (created_task == MQX_NULL_TASK_ID) {
      /* task creation failed */
   } /*Endif*/

#if EVENTA_DVFS_MODE
    result = _ep_dvfs_set_mode(created_task, EVENTA_DVFS_MODE);
	if (result != MQX_OK) {
		/* Error setting DVFS mode for task */
		printf("\nError setting DVFS mode for task %d.\n", created_task);
	} /* Endif */
#endif

   created_task = _task_create(0, EVENTB_INDEX, 0);
   if (created_task == MQX_NULL_TASK_ID) {
      /* task creation failed */
   } /*Endif*/

#if EVENTB_DVFS_MODE
	result = _ep_dvfs_set_mode(created_task, EVENTB_DVFS_MODE);
	if (result != MQX_OK) {
		/* Error setting DVFS mode for task */
		printf("\nError setting DVFS mode for task %d.\n", created_task);
	} /* Endif */
#endif


   /* create kernel log  */
   log_result = _klog_create((_mqx_uint)120000, (_mqx_uint)LOG_OVERWRITE);
   if (log_result != MQX_OK) {
      /* log could not be created */
   } /*Endif*/
   /* define kernel logging */
   _klog_control((uint_32)0xffffffff, FALSE);
   _klog_control(KLOG_ENABLED |
                 KLOG_FUNCTIONS_ENABLED |
                 KLOG_INTERRUPTS_ENABLED |
                 KLOG_SYSTEM_CLOCK_INT_ENABLED |
                 KLOG_CONTEXT_ENABLED |
                 KLOG_TASKING_FUNCTIONS |
                 KLOG_ERROR_FUNCTIONS |
                 KLOG_MESSAGE_FUNCTIONS |
                 KLOG_INTERRUPT_FUNCTIONS |
                 KLOG_MEMORY_FUNCTIONS |
                 KLOG_TIME_FUNCTIONS |
                 KLOG_EVENT_FUNCTIONS |
                 KLOG_NAME_FUNCTIONS |
                 KLOG_MUTEX_FUNCTIONS |
                 KLOG_SEMAPHORE_FUNCTIONS |
                 KLOG_WATCHDOG_FUNCTIONS | 
                 KLOG_PMU_FUNCTIONS, TRUE);
   
#if DEMO_POWER_DOWN
	result = _ep_pmu_set_pwrdn_mode (MQX_PMU_POWER_DOWN_MODE_1);
	if (result != MQX_OK) {
		/* Error setting power down mode */
		printf("\nError setting power down mode.\n");
	} /* Endif */

#if DEMO_SLOW_DOWN
   result = _ep_pmu_set_timer_thrshld(DEMO_POWER_DOWN);
   if (result != MQX_OK) {
      /* Error setting timer thrshld */
      printf("\nError setting timer thrshld.\n");
   } /* Endif */

   result = _ep_pmu_set_max_slw_dwn(DEMO_SLOW_DOWN);
   if (result != MQX_OK) {
      /* Error setting max. slow down clock */
      printf("\nError setting max. slow down clock.\n");
   } /* Endif */
#endif
#else
	result = _ep_pmu_set_pwrdn_mode (MQX_PMU_POWER_DOWN_MODE_0);
	if (result != MQX_OK) {
		/* Error setting power down mode */
		printf("\nError setting power down mode.\n");
	} /* Endif */
#endif /* POWER_DOWN */

#if DEMO_GLOBAL_DVFS_MODE
    result = _ep_dvfs_set_mode(0, DEMO_GLOBAL_DVFS_MODE);
    if (result != MQX_OK) {
      /* Error setting global DVFS mode */
      printf("\nError setting global DVFS mode.\n");
   } /* Endif */
#endif

#if DEMO_AUTO_DVFS
    result = _ep_dvfs_set_auto (MQX_PMU_DVFS_AUTO_ENABLE);
    if (result != MQX_OK) {
		/* Error setting power down mode */
		printf("\nError setting auto dvfs mode.\n");
	} /* Endif */
#endif

   /*
   ** LOOP - 
   */
   while (TRUE) {
      msg_ptr = _msg_alloc((_pool_id)MsgPool_pool_id);
      if (msg_ptr == NULL) {
         /* No available message buffer */
      } /*Endif*/
      msg_ptr->SOURCE_QID = msg_ptr->TARGET_QID;
      msg_ptr->TARGET_QID = Sender_Queue_qid;
      _msgq_send(msg_ptr);

      /*
      ** Service the message queue - Main_Queue
      */
      msg_ptr = _msgq_receive(Main_Queue_qid, (_mqx_uint)NO_TIMEOUT);
      /* process message End_msg */
      _msg_free(msg_ptr);

   } /* Endwhile */ 
} /*EndBody*/

uint_32 dummy[100];
void Loadfunction
   (
      uint_32  parameter
   )
{
	int i;
	for(i=0;i<=parameter;i++)
	{
		dummy[i%100] = i*11;
	}
	for(i=0;i<=parameter;i++)
	{
		dummy[i%100] = i*11;
	}
	for(i=0;i<=parameter;i++)
	{
		dummy[i%100] = i*11;
	}
	for(i=0;i<=parameter;i++)
	{
		dummy[i%100] = i*11;
	}
	for(i=0;i<=parameter;i++)
	{
		dummy[i%100] = i*11;
	}
}



/* End of File */
