/**********************************************************************
*    This file was generated by Design Tool a product of: 
*       ARC International  
*       http://www.ARC.com/         
*                              
*       Mon Mar 12 09:32:23 2007
*   
*       Copyright (c) ARC International  
*       All rights reserved    
*   
*       This software embodies materials and concepts which are
*       confidential to ARC International and is made
*       available solely pursuant to the terms of a written license
*       agreement with ARC International.
*   
*   ********************************************************************/
/* 
*  Resources  -   Number -  Memory Required
*  Kernel       -   N/A       -  0x274c
*  Tasks        - 11       -  0x2530
*  Msg Pools    -  1 of 2  -   0x1a4
*  Msg Queues   -  3 of 12   -  0x1a0
*  Mutexes       -  1    -  0x24
*  Semaphores   -  1 of 10  -  0x280
*  Events       -  1 of 10   -    0x2a0
*  Logs         -  1 of 16    -  0x1344
*  	   Total:  0x6848 or 26696
*/ 
#include <mqx.h>
#include <bsp.h>
#include <message.h>
#include <errno.h>
#include <mutex.h>
#include <sem.h>
#include <event.h>
#include <log.h>
#include <klog.h>
#include "demo.h"

/*   Task Code -  Responder     */

/*TASK---------------------------------------------------------------
*
* Task Name   :  Responder
* Comments    :  
*
*END*--------------------------------------------------------------*/

void Responder
   (
      uint_32  parameter
   )
{
   MESSAGE_HEADER_STRUCT_PTR   msg_ptr;

   Responder_Queue_qid = _msgq_open(MSGQ_FREE_QUEUE, SIZE_UNLIMITED);
   if (Responder_Queue_qid == MSGQ_NULL_QUEUE_ID) {
      /* queue could not be opened */
   } /*Endif*/
   /*
   ** LOOP - 
   */
   while (TRUE) {

#if RESPONDER_DELAY
	  Loadfunction(RESPONDER_DELAY);
#endif
      /*
      ** Service the message queue - Responder_Queue
      */
      msg_ptr = _msgq_receive(Responder_Queue_qid, (_mqx_uint)NO_TIMEOUT);
      /* process message Respond_msg */
      msg_ptr->SOURCE_QID = msg_ptr->TARGET_QID;
      msg_ptr->TARGET_QID = Sender_Queue_qid;
      _msgq_send(msg_ptr);


      printf(".");
   } /* Endwhile */ 
} /*EndBody*/

/* End of File */
