/**********************************************************************
*    This file was generated by Design Tool a product of: 
*       ARC International  
*       http://www.ARC.com/         
*                              
*       Mon Mar 12 09:32:23 2007
*   
*       Copyright (c) ARC International  
*       All rights reserved    
*   
*       This software embodies materials and concepts which are
*       confidential to ARC International and is made
*       available solely pursuant to the terms of a written license
*       agreement with ARC International.
*   
*   ********************************************************************/
/* 
*  Resources  -   Number -  Memory Required
*  Kernel       -   N/A       -  0x274c
*  Tasks        - 11       -  0x2530
*  Msg Pools    -  1 of 2  -   0x1a4
*  Msg Queues   -  3 of 12   -  0x1a0
*  Mutexes       -  1    -  0x24
*  Semaphores   -  1 of 10  -  0x280
*  Events       -  1 of 10   -    0x2a0
*  Logs         -  1 of 16    -  0x1344
*  	   Total:  0x6848 or 26696
*/ 
#include <mqx.h>
#include <bsp.h>
#include <message.h>
#include <errno.h>
#include <mutex.h>
#include <sem.h>
#include <event.h>
#include <log.h>
#include <klog.h>
#include "demo.h"
#include "pmu.h"

/*   Task Code -  Sender     */

/*TASK---------------------------------------------------------------
*
* Task Name   :  Sender
* Comments    :  
*
*END*--------------------------------------------------------------*/

void Sender
   (
      uint_32  parameter
   )
{
   MESSAGE_HEADER_STRUCT_PTR   msg_ptr;
   _task_id    created_task;
   uint_32 result;

   Sender_Queue_qid = _msgq_open(MSGQ_FREE_QUEUE, SIZE_UNLIMITED);
   if (Sender_Queue_qid == MSGQ_NULL_QUEUE_ID) {
      /* queue could not be opened */
   } /*Endif*/
   created_task = _task_create(0, RESPONDER_INDEX, 0);
   if (created_task == MQX_NULL_TASK_ID) {
      /* task creation failed */
   } /*Endif*/

#if RESPONDER_DVFS_MODE
	result = _ep_dvfs_set_mode(created_task, RESPONDER_DVFS_MODE);
	if (result != MQX_OK) {
		/* Error setting DVFS Mode */
		printf("\nError setting DVFS mode for task ID 0x%x.\n", created_task);
	} /* Endif */
#endif

   /*
   ** LOOP - 
   */
   while (TRUE) {
      /*
      ** Service the message queue - Sender_Queue
      */
      msg_ptr = _msgq_receive(Sender_Queue_qid, (_mqx_uint)NO_TIMEOUT);
      /* process message Start_msg */

#if SENDER_DELAY
       Loadfunction(SENDER_DELAY);
#endif

	  _time_delay_ticks((_mqx_uint)3);
      msg_ptr->SOURCE_QID = msg_ptr->TARGET_QID;
      msg_ptr->TARGET_QID = Responder_Queue_qid;
      _msgq_send(msg_ptr);



   } /* Endwhile */ 
} /*EndBody*/

/* End of File */
