
/* Generated by mcsg V1.0.0
 * 
 */

#include "vr_application_include.h"


static int vr_meta_channels_init (void);

VR_CONST int vr_n_channels = 4;
uint32_t render_channel0_dest_threads [] = { swarch_thd_rendermain0_thread_id };
uint32_t display_channel0_dest_threads [] = { swarch_thd_displaymain_thread_id };
uint32_t render_channel1_dest_threads [] = { swarch_thd_rendermain1_thread_id };
uint32_t display_channel1_dest_threads [] = { swarch_thd_displaymain_thread_id };
VR_CONST VrMetaChannel * vr_meta_channel[5] = { 0, 0, 0, 0, 0 };
void * vr_channel[5] = { 0, 0, 0, 0, 0 };

/* Auxiliary code for channel display_channel0_id */
VrCircularBuffer_display_channel0 display_channel0_channel_impl __attribute__ ((section(".display_channel0"), aligned(4)));
int display_channel0_channel_impl_send_count = 65536;
int display_channel0_channel_impl_full_count = 0;
int display_channel0_channel_impl_recv_count = 65536;

/* Auxiliary code for channel display_channel1_id */
VrCircularBuffer_display_channel1 display_channel1_channel_impl __attribute__ ((section(".display_channel1"), aligned(4)));
int display_channel1_channel_impl_send_count = 196608;
int display_channel1_channel_impl_full_count = 0;
int display_channel1_channel_impl_recv_count = 196608;

int
vr_channel_send (vr_channel_t __vr_channel_id, void * __vr_msg, int __vr_msg_size, int flags)
{
#define __vr_channel_impl ((void *) vr_get_channel_impl (__vr_channel_id))
  int __vr_result = -1;

  return __vr_result;
#undef __vr_channel_impl
}

int
vr_channel_receive (vr_channel_t __vr_channel_id, void * __vr_msg, int __vr_msg_size, int flags)
{
#define __vr_channel_impl ((void *) vr_get_channel_impl (__vr_channel_id))
  int __vr_result = -1;

  switch (__vr_channel_id)
    {

    case display_channel0_id:
      do 
        {
          VrCircularBufferNoSync_rp_read (((VrCircularBuffer_display_channel0 *) __vr_channel_impl), 256, __vr_msg, __vr_msg_size, 1, 0, __vr_result, __vr_result);

          if (__vr_result==__vr_msg_size) {
            display_channel0_channel_impl_recv_count++;
          }
        } while(0);
      break;

    case display_channel1_id:
      do 
        {
          VrCircularBufferNoSync_rp_read (((VrCircularBuffer_display_channel1 *) __vr_channel_impl), 256, __vr_msg, __vr_msg_size, 1, 0, __vr_result, __vr_result);

          if (__vr_result==__vr_msg_size) {
            display_channel1_channel_impl_recv_count++;
          }
        } while(0);
      break;
    }
  return __vr_result;
#undef __vr_channel_impl
}

int
vr_channel_setup_global (void)
{

  if (vr_meta_channels_init () < 0)
    return -1;

  return 0;
}

int
vr_channel_setup_global_as_receiver (void)
{

  return 0;
}

int
vr_channel_setup_sender_process (void)
{


  return 0;
}

int
vr_channel_setup_receiver_process (void)
{
  void ** __vr_channel_impl_ptr VR_UNUSED_VARIABLE_ATTRIBUTE = 0;


  do
    {
      __vr_channel_impl_ptr = &vr_get_channel_impl (display_channel0_id);
      * __vr_channel_impl_ptr = (void *) (&display_channel0_channel_impl);
    }
  while (0);

  do
    {
      __vr_channel_impl_ptr = &vr_get_channel_impl (display_channel1_id);
      * __vr_channel_impl_ptr = (void *) (&display_channel1_channel_impl);
    }
  while (0);

  return 0;
}

int
vr_channel_setup_sender_thread (uint32_t thread_id)
{

  switch (thread_id)
    {
    case swarch_thd_displaymain_thread_id:

      break;
    }

  return 0;
}

int
vr_channel_setup_receiver_thread (uint32_t thread_id)
{

  switch (thread_id)
    {
    case swarch_thd_displaymain_thread_id:

      do
        {
          void ** __vr_channel_impl_ptr VR_UNUSED_VARIABLE_ATTRIBUTE = &vr_get_channel_impl (display_channel0_id);
        }
      while (0);

      do
        {
          void ** __vr_channel_impl_ptr VR_UNUSED_VARIABLE_ATTRIBUTE = &vr_get_channel_impl (display_channel1_id);
        }
      while (0);

      break;
    }

  return 0;
}

int
vr_meta_channels_init (void)
{

  if (vr_meta_channel_init (0, "NULL_channel_id", 0, 0) < 0)
    return -1;

  if (vr_meta_channel_init (render_channel0_id, "render_channel0", 1, render_channel0_dest_threads) < 0)
    return -1;
  if (vr_meta_channel_init (display_channel0_id, "display_channel0", 1, display_channel0_dest_threads) < 0)
    return -1;
  if (vr_meta_channel_init (render_channel1_id, "render_channel1", 1, render_channel1_dest_threads) < 0)
    return -1;
  if (vr_meta_channel_init (display_channel1_id, "display_channel1", 1, display_channel1_dest_threads) < 0)
    return -1;

  return 0;
}
