
/* Generated by mcsg V1.0.0
 * 
 */

#include "vr_application_include.h"

VR_CONST int vr_n_mutexes = 0;
void * vr_mutex[1] = { 0 };
int
vr_mutex_lock (vr_mutex_t __vr_mutex_id)
{
#define __vr_mutex_impl ((void *) vr_get_mutex_impl (__vr_mutex_id))
  int __vr_result = -1;
  return __vr_result;
#undef __vr_mutex_impl
}

int
vr_mutex_trylock (vr_mutex_t __vr_mutex_id)
{
#define __vr_mutex_impl ((void *) vr_get_mutex_impl (__vr_mutex_id))
  int __vr_result = -1;
  return __vr_result;
#undef __vr_mutex_impl
}

int
vr_mutex_unlock (vr_mutex_t __vr_mutex_id)
{
#define __vr_mutex_impl ((void *) vr_get_mutex_impl (__vr_mutex_id))
  int __vr_result = -1;
  return __vr_result;
#undef __vr_mutex_impl
}

int
vr_mutex_setup (void)
{
  int __vr_result = 0;


  return __vr_result;
}
