
/* Generated by mcsg V1.0.0
 * 
 */

#include "vr_application_include.h"

VR_CONST int vr_n_queues = 0;
void * vr_queue[1] = { 0 };

int
vr_queue_enqueue (vr_queue_t __vr_queue_id, void * __vr_node)
{
#define __vr_queue_impl ((void *) vr_get_queue_impl (__vr_queue_id))
  int __vr_result = 0;
  return __vr_result;
#undef __vr_queue_impl
}

void *
vr_queue_dequeue (vr_queue_t __vr_queue_id)
{
#define __vr_queue_impl ((void *) vr_get_queue_impl (__vr_queue_id))
  void * __vr_result = 0;
  return __vr_result;
#undef __vr_queue_impl
}

int
vr_queue_is_empty (vr_queue_t __vr_queue_id)
{
#define __vr_queue_impl ((void *) vr_get_queue_impl (__vr_queue_id))
  int __vr_result = 0;
  return __vr_result;
#undef __vr_queue_impl
}

int
vr_queue_get_size (vr_queue_t __vr_queue_id)
{
#define __vr_queue_impl ((void *) vr_get_queue_impl (__vr_queue_id))
  int __vr_result = 0;
  return __vr_result;
#undef __vr_queue_impl
}

int
vr_queue_setup (void)
{
  int __vr_result = 0;


  return __vr_result;
}
