
/**************************************************************************
 *
 * Generated by mcsg
 * Version 1.0.0
 * Build trunk
 * Fri Jul 18 16:04:30 PDT 2008
 * ARC International (c) 2008
 * This is a generated file. All manual edits will be lost.
 *
 **************************************************************************/


/*
 * This file contains the fully-qualified names of processors and memory banks 
 * and busses defined in the 'hwarch' hardware architecture. These names are
 * used as follows : 
 * - processor names are required by the software architecture to create OSes
 * - memory banks names are required when mapping sections and
     some coordination API objects

****** PROCESSORS ******

hwarch.SoC.cpu0
hwarch.SoC.cpu1
hwarch.SoC.cpu2
hwarch.SoC.cpu3

****** MEMORY BANKS ******

hwarch.SoC.imemory_model

****** BUSSES ******

hwarch.SoC.bgt_bus
hwarch.SoC.bgi_bus
hwarch.SoC.memarb_bus
hwarch.SoC.arbi_bus
hwarch.SoC.arbt_bus
hwarch.SoC.sdram_ctrl_bus
hwarch.SoC.uart0_bus
hwarch.SoC.sdram_bus
hwarch.SoC.cpu0_bus
hwarch.SoC.cpu1_bus
hwarch.SoC.cpu2_bus
hwarch.SoC.cpu3_bus


*/

