
/**************************************************************************
 *
 * Generated by mcsg
 * Version 1.0.0
 * Build trunk
 * Fri Jul 18 16:04:30 PDT 2008
 * ARC International (c) 2008
 * This is a generated file. All manual edits will be lost.
 *
 **************************************************************************/


/*
 * This file contains the fully-qualified names of processors and memory
 * components defined in the 'hwarch' hardware architecture.
 * These names are used as follows : 
 * - processor names are required by the software architecture to create OSes
 * - memory components and the bank paths are required when mapping
 *   sections and some coordination API objects

****** PROCESSORS ******

cpu0.core		family: arc700
cpu1.core		family: arc700
cpu2.core		family: arc700
cpu3.core		family: arc700

****** MEMORY COMPONENTS and BANK PATHS ******

imemory_model		component type: memory_model
	xsdram_memoryMapRef.xsdram_Bank0.bank0 0x00000000 0x10000000 32


*/

